### ISSUE TITLE
Eingabefeld für die Artikel-Id

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/quick_navigation#1]
Wäre es evtl. noch einfach möglich ein Eingabefeld für die Artikel-ID mit einzufügen, so wie bei Redaxo 4 auch?
Damit sollte man dann direkt zum Content des Artikels kommen.

**Comment by brandes-webdesign** [comment]
Findet das zusätzliche Eingabefeld für die Artikel-ID kein weiteren Nutzen?
Ich wäre auch bereit, die notwendige Stunde Arbeit dafür zu zahlen.

**Comment by tbaddade** [comment]
> Wäre es evtl. noch einfach möglich ein Eingabefeld für die Artikel-ID mit einzufügen

Ich habe es bisher nie benötigt und fand es schon zu Rex4 Zeiten überflüssig. Auch hält sich das Verlangen anderer User in Grenzen. Daher habe ich die Suche nach der Id nun im [Watson](https://github.com/tbaddade/redaxo_watson) aufgenommen.

Wenn das Interesse steigen sollte, können wir sicherlich noch eine andere Lösung finden.

**Comment by alexplusde** [comment]
Och, hin und wieder genutzt wurde es auch bei uns, aber die große Masse scheinbar wirklich nicht. Aber dass es in Watson drin ist, ist natürlich auch gut.

**Comment by brandes-webdesign** [comment]
Dafür noch ein weiteres Addon installieren halte ich für mich persönlich für nicht sinnvoll.
Von daher muss ich mich da wohl mal selber austoben im Addon und das eigenständig einbauen.

Ich habe das Eingabefeld bisher sehr intensiv genutzt. Täglich mehrere dutzend Male.
Ich hab die letzten Jahre praktisch keine inhaltlichen Änderungen an irgendwelchen Webseite gemacht, wenn der Kunde mir nicht die Artikel-ID mitgeschickt hat.
Bisher war die ja bei mir auch immer in der URL mit drinnen, aber diese URL Umschreibung gibt es anscheinend leider auch nicht mehr. Also dieses "1-0-Home.html". 
Oder weiß da jemand, ob es das doch noch gibt als alternative für yRewrite ?

**Comment by alexplusde** [comment]
Die Umschreibung war nur eine htaccess-Regel, meines Wissens, mehr nicht.
· von unterwegs gesendet ·
Am 14.09.2016 12:33 nachm. schrieb brandes-webdesign <notifications@github.com>:Dafür noch ein weiteres Addon installieren halte ich für mich persönlich für nicht sinnvoll.
Von daher muss ich mich da wohl mal selber austoben im Addon und das eigenständig einbauen.

Ich habe das Eingabefeld bisher sehr intensiv genutzt. Täglich mehrere dutzend Male.
Ich hab die letzten Jahre praktisch keine inhaltlichen Änderungen an irgendwelchen Webseite gemacht, wenn der Kunde mir nicht die Artikel-ID mitgeschickt hat.
Bisher war die ja bei mir auch immer in der URL mit drinnen, aber diese URL Umschreibung gibt es anscheinend leider auch nicht mehr. Also dieses "1-0-Home.html". 
Oder weiß da jemand, ob es das doch noch gibt als alternative für yRewrite ?

**Comment by brandes-webdesign** [comment]
Danke, Alex. 
Stimmt eigentlich. Muss ich mal testen.
