### ISSUE TITLE
QuickNavigation löscht MetaInfo Felder im Medienpool

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#103]
Weitere Infos hier
https://github.com/redaxo/redaxo/issues/2486

**Comment by skerbis** [comment]
Vielleicht hat es was damit zu tun: 
31.01.2019 14:49:08 | Error | Call to a member function isPopup() on null | redaxo/src/addons/quick_navigation/boot.php | 21

**Comment by skerbis** [comment]
Würde mich über Hilfe freuen. Ich kann nicht feststellen wie der Fehler zustande kommt.

**Comment by staabm** [comment]
vllt findet sich im slack irgendein javascript guru der zeit hat das zu debuggn

**Comment by skerbis** [comment]
@staabm wenn ich hier https://github.com/FriendsOfREDAXO/quick_navigation/blob/39cfc7ffc8102a6c028aa7be100124e264e7ed0e/assets/quicknavi.js#L4
post durch Get ersetze scheint der Fehler nicht aufzutreten. Kannst du das bestätigen?

**Comment by skerbis** [comment]
@Goldfischpeter kannst du das mal bei Dir testen … aus $.post mach $.get

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/archive/3.5.5.zip
