### ISSUE TITLE
Call to undefined method rex_api_quicknavigation_render::getUrlParams()

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/quick_navigation#104]
Bekomme den Fehler auf einer 5.4er Instanz

"Call to undefined method rex_api_quicknavigation_render::getUrlParams()"

**Comment by skerbis** [comment]
Ok. Scheint es in der 5.4er noch nicht zu geben

**Comment by staabm** [comment]
d.h. ist die min-redaxo version nicht korrekt?

**Comment by skerbis** [comment]
Korrekt. die Methode kam mit 5.5. Ich habe das Aden auf min. 5.5 jetzt gesetzt.
