### ISSUE TITLE
Feature Wunsch: optionale Erweiterung der Historie um YForm-Tabellen

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/quick_navigation#108]
Wenn YForm-Tabellen die Felder `updatedate` und `updateuser` mitbringen könnten man sie in die Historie einklinken. Das wäre für tabellenlastige Projekte ein Gewinn.

**Comment by skerbis** [comment]
Da dies nicht per default gegeben ist, sehe ich hier keine allgemein gültige Möglichkeit. Du kannst dir aber per ep einen eignen Button einschmuggeln

**Comment by tbaddade** [comment]
@skerbis Du kannst via `hasValue()` prüfen, ob ein Feld existiert.

**Comment by skerbis** [comment]
@tbaddade hast du ein Beispiel?

**Comment by skerbis** [comment]
Aber darüber hinaus müsste es aber auch ein weiteres Feld geben, das es ermöglicht den Inhalt des Datensatzes zu identifizieren name title etc.

**Comment by skerbis** [comment]
Wäre das nicht was für: https://github.com/danspringer/mf_lastchanges ??

**Comment by tbaddade** [comment]
> Aber darüber hinaus müsste es aber auch ein weiteres Feld geben, das es ermöglicht den Inhalt des Datensatzes zu identifizieren name title etc.

Jepp … In Watson gehe ich zum Beispiel diese Felder durch.
https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Workflows/YForm/YFormSearch.php#L71

**Comment by skerbis** [comment]
Nach einigen Tests komme ich zu dem Ergebnis, dass eine History hier nicht viel Sinn ergibt. 
Nicht jede Tabelle bzw. Datensatz liefert Datumsangaben. Wenn dies Pflichtfelder wären also created und updated würde es ok sein. Stattdessen kann ich mir vorstellen, dass wir einen Trick anbieten um eine Tabelle zu beobachten und zeigen, wie man mittels EP einen Button hinzufügt.
