### ISSUE TITLE
 Error | Class 'rex_minibar_element_quicknavi' not found

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#109]
Ich setze den Fehler mal hier rein, da ich nicht weiß ob es ein Problem der Quicknavi oder der Minibar ist. 

Erhalte folgenden Fehler direkt nach Installation der minibar: 

> 26.06.2019 13:37:33 | Error | Class 'rex_minibar_element_quicknavi' not found | redaxo/src/addons/quick_navigation/boot.php | 52

Das Element wird aber geladen? 
@staabm 
@gharlan 

Der Check ob die Minibar da ist erfolgt hier: 
https://github.com/FriendsOfREDAXO/quick_navigation/blob/ec9c5668bab11431c5699a8d9cd7943e25e5ba47/boot.php#L50

**Comment by tbaddade** [comment]
> Erhalte folgenden Fehler direkt nach Installation der minibar:

Du erhält den Fehler im Backend?

**Comment by skerbis** [comment]
Im Systemlog wird er gelistet

**Comment by skerbis** [comment]
scheint nicht mehr zu passieren REDAXO 5.8.1
