### ISSUE TITLE
QuickNavi nur in der Strukturansicht anzeigen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/quick_navigation#11]

**Comment by tbaddade** [comment]
@olien Welchen Grund gibt es dafür?

**Comment by olien** [comment]
war das nicht immer so? - aber eigentlich ist es auch egal...

**Comment by tbaddade** [comment]
> war das nicht immer so? 

In R4 schon, was ich aber eher unpraktisch fand. Wenn du das für sinnvoll hälst, könnte man sicherlich eine Einstellungsseite aufmachen.

**Comment by olien** [comment]
Ich gewöhne mich dran...
