### ISSUE TITLE
Styles verloren gegangen?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#110]
## Normal 

**Aktuell**

<img width="384" alt="Bildschirmfoto 2019-08-22 um 17 34 47" src="https://user-images.githubusercontent.com/338267/63528399-2520ef80-c503-11e9-9473-317af191012c.png">

---

**War mal**

<img width="363" alt="Bildschirmfoto 2019-08-22 um 17 34 27" src="https://user-images.githubusercontent.com/338267/63528381-1afef100-c503-11e9-8232-70ecd8cfa2a1.png">

--- 

### Focus

**Aktuell**

<img width="241" alt="Bildschirmfoto 2019-08-22 um 17 36 58" src="https://user-images.githubusercontent.com/338267/63528606-88128680-c503-11e9-85b1-704ad15a9d97.png">

---

**War mal**

<img width="244" alt="Bildschirmfoto 2019-08-22 um 17 36 28" src="https://user-images.githubusercontent.com/338267/63528688-aa0c0900-c503-11e9-8b2a-131f321cb011.png">

---

Auch bei der Dropliste scheint was verloren gegangen zu sein.

**Comment by skerbis** [comment]
Das ist aber schon lange so. Du hattest doch in yakme eigene Stile.

**Comment by skerbis** [comment]
Hierzu zur Erinnerung: https://github.com/FriendsOfREDAXO/quick_navigation/issues/81
Ich habe aber jetzt die Default Stile für die Buttons wieder drin. Deine Screens oben scheinen aber von Yakme zu kommen

**Comment by tbaddade** [comment]
Stimmt :) ... hatte gester nur schnell mal
