### ISSUE TITLE
Quick Navigation wird im Login angezeigt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#111]
https://github.com/FriendsOfREDAXO/2factor_auth/issues/33

Bitte mit aktueller Github-Version testen. Ich bitte um Rückmeldung 
@Geri2017

**Comment by staabm** [comment]
Ps: ich wer auch mal auf 2factor auth seite schauen obs dort ggf. eine einfache/schöne lösung gibt.

Ich vermute dass z.b. Watson ein ähnliches problem hat

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/archive/3.7.0.zip
