### ISSUE TITLE
qn+sked: HTML Syntax verkehrt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/quick_navigation#112]
![image](https://user-images.githubusercontent.com/3855487/66513794-279fce80-eadc-11e9-8b39-6dee2419c287.png)

Der Text darf nicht in das Icon, sondern muss daneben, damit die Schrift korrekt gerendert wird.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/commit/cf5062eabbad7311c06f01e413753fac67620217
