### ISSUE TITLE
Design Bug

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#113]
Erscheint, wenn man die Identität bei Benutzern wechselt.

<img width="358" alt="Bildschirmfoto 2019-11-25 um 09 42 06" src="https://user-images.githubusercontent.com/338267/69542070-ec256a80-0f8a-11ea-91c1-a3315c892304.png">

**Comment by skerbis** [comment]
Welcher Browser? ... Bei mir stimmt alles, getestet in Chrome und Safari 
<img width="437" alt="Bildschirmfoto 2019-11-25 um 16 47 05" src="https://user-images.githubusercontent.com/791247/69555312-43cfd000-0fa3-11ea-83ed-ab2925d8173e.png">

**Comment by tbaddade** [comment]
sorry … war was Projekt eigenes
