### ISSUE TITLE
Slice speichern: CSRF-Schutz fehlerhaft

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#115]
Editiert man einen Slice und der CSRF Token ist nicht mehr gültig, dann wird in den PJAX-Container die komplette Seite geladen. Die Hauptnavigation sieht man dann doppelt.

Quciknavigatin lädt die Meldung dann in Kopfbereich der Contentseite.

**Screenshot Quellcode**
<img width="219" alt="Bildschirmfoto 2020-02-03 um 10 17 58" src="https://user-images.githubusercontent.com/338267/73640626-e628c580-466e-11ea-90da-97de97ff855b.png">

**Screenshot oberer Teil**
<img width="1540" alt="Bildschirmfoto 2020-02-03 um 10 18 53" src="https://user-images.githubusercontent.com/338267/73640697-06f11b00-466f-11ea-9e4f-e065e5c15b3e.png">

**Screenshot unterer Teil**
<img width="538" alt="Bildschirmfoto 2020-02-03 um 10 18 23" src="https://user-images.githubusercontent.com/338267/73640723-12444680-466f-11ea-8c43-5aadb3548b40.png">

**Comment by tbaddade** [comment]
@skerbis Findest du demnächst Zeit das anzugehen?

**Comment by skerbis** [comment]
@tbaddade da brauche ich Hilfe. Ich weiß ehrlich gesagt, nicht wo ich da ansetzen muss.

**Comment by tbaddade** [comment]
> Wie kann ich diesen Fehler reproduzieren?

1/ Artikelinhalt in einem separaten Browsertab öffnen und dort einen Slice zum Editieren öffnen.
2/ Nichts machen
3/ Warten (Tab ignorieren)
4/ Irgendwann ist der Token abgelaufen (genau Zeit müsste @gharlan wissen) und dann versuchen den Slice zu speichern.

**Comment by skerbis** [comment]
Hmm bei mir wird nichts ungültig. Dennoch kann es sein dass die api die komplette Seite zurückgibt obwohl ja „nur“ die quicknavi angefragt wurde? Sollte die api bei dem Ajax Aufruf dann nicht besser nur n false liefern? @staabm @gharlan

**Comment by gharlan** [comment]
> Editiert man einen Slice und der CSRF Token ist nicht mehr gültig

Wobei beim Slice editieren gar kein CSRF-Schutz vorhanden ist, also auch kein Token geprüft wird. Das muss noch irgendwo anders herkommen. Vermutlich ist es der CSRF-Schutz der Quicknavi-Api-Func.

> Irgendwann ist der Token abgelaufen (genaue Zeit müsste @gharlan wissen) und dann versuchen den Slice zu speichern.

Die Tokens laufen nur ab, wenn die Session abgelaufen ist. Dann müsste aber auch die Login-Seite kommen.

Ich kann mir das noch nicht so recht erklären.

**Comment by skerbis** [comment]
Ich habe alles erdenkliche versucht es bei mir zu reproduzieren- ohne Erfolg. Das scheint ein sehr seltener Fall zu sein.

**Comment by tbaddade** [comment]
> Das scheint ein sehr seltener Fall zu sein.

Selten ist es wirklich nicht. Es ist nur selten, dass der Slice lang genug offen bleibt.

**Comment by skerbis** [comment]
@alexplusde kannst du bitte testen ob's besser wird, wenn hier false steht? 

https://github.com/FriendsOfREDAXO/quick_navigation/blob/924f68bb38a703d5e9e39170b77f93ecca83cb04/lib/api_quicknavigation_render.php#L13

Wie oben erwähnt, konnte ich es nicht reproduzieren. Daher bitte mal prüfen.

**Comment by alexplusde** [comment]
gezielt reproduzierbar:

* Backend in 2 Tabs öffnen
* In Tab 1 ein Slice öffnen
* In Tab 2 abmelden und anmelden
* In Tab 1 ein Slice speichern

**Comment by skerbis** [comment]
Das ist aber ein ungewöhnliches Szenario.

**Comment by alexplusde** [comment]
@skerbis das dient nur zur Simulation, wenn der Token ungültig wird.

Hier war es Chrome bei mir mit dem Fehler.

**Comment by skerbis** [comment]
Kannst du bitte das oben beschriebene testen?

**Comment by alexplusde** [comment]
Nein, denn ich habe keinen Safari.

**Comment by gharlan** [comment]
Er meinte diesen Test: https://github.com/FriendsOfREDAXO/quick_navigation/issues/115#issuecomment-628498769

**Comment by skerbis** [comment]
Ja und? @alexplusde hast du getestet?

**Comment by skerbis** [comment]
@alexplusde ping?

**Comment by alexplusde** [comment]
Ja, gezielt reproduzierbar wie oben beschrieben in meinem Kommentar.

**Comment by alexplusde** [comment]
Achso, ob da false stehen soll... 100 Mal überlesen... ne, konnte ich noch nicht testen.

**Comment by skerbis** [comment]
Scheint sehr selten zu passieren. Ich close erstmal.

**Comment by tbaddade** [comment]
> Scheint sehr selten zu passieren. Ich close erstmal.

Hattest du etwas angepasst? So selten ist das nicht. 
Zumindest das Verhalten was ich oben beschrob.

**Comment by skerbis** [comment]
Niemand konnte mir helfen es zu reproduzieren. Bei mir hab ich es nicht geschafft es wie oben beschrieben nachzuvollziehen.  Das AddOn ist aber auch schon an einigen Stellen anders. Ich bat darum es mal zu testen wenn https://github.com/FriendsOfREDAXO/quick_navigation/issues/115#issuecomment-628498769 auf False gesetzt wurde.

**Comment by skerbis** [comment]
Das AddOn.ist jetzt komplett umgebaut. 
In der API Class ist CSRF auf false gesetzt. 
@tbaddade und @alxndr-w bitte mit der aktuellen GitHub-Version 4 und REDAXO 5.12 testen.

**Comment by alxndr-w** [comment]
Geht klar.

**Comment by skerbis** [comment]
schon wer getestet? @alxndr-w @tbaddade ?

**Comment by alxndr-w** [comment]
Noch nicht, die 5.12 teste ich gerade erst richtig und damit auch das hier.

**Comment by skerbis** [comment]
Da sich hier nichts tut und sich sonst keiner mehr gemeldet hat, gehe ich davon aus, dass das Problem sich mit den letzten Versionen erledigt hat. Daher close.

**Comment by alxndr-w** [comment]
Ich update gerade bewusst nicht auf die 5.12.X, daher von mir kein Feedback möglich.
