### ISSUE TITLE
REDAXO 5.9 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#116]
Quicknavi wird nach Installation nicht angezeit, Log meldet: 

> 04.02.2020 15:07:11 | Error | Call to a member function getCode() on null | redaxo/src/addons/quick_navigation/fragments/quick_articles.php | 54

Lässt sich nur beheben durch Cache löschen. 

@gharlan hast du ne Idee?

**Comment by gharlan** [comment]
So spontan nicht. Irgendwie wurde da eine Clang nicht gefunden.

**Comment by staabm** [comment]
falls du das problem reproduzieren kannst, mach dir mal ne debug ausgabe in die zeile und schau was in $data drinnen steht/stand

https://github.com/FriendsOfREDAXO/quick_navigation/blob/5db356c4fa0581a02653251a7fba96ae2251e186/fragments/quick_articles.php#L54

**Comment by skerbis** [comment]
Habe nochmal eine frische Installation gemacht. Da tritt das nicht auf. 
Falls es noch mal auftritt, öffne ich das issue wieder. 

Seltsam ist es jedoch schon. Er hätte nicht so weit kommen sollen, weil ja noch keine Kategorien zu diesem Zeitpunkt angelegt sind.
