### ISSUE TITLE
Min-php version in package.yml notieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/quick_navigation#117]

**Comment by skerbis** [comment]
Sollte doch dem vom REDAXO entsprechen? Oder ist hier was, was ich übersehe?

**Comment by tbaddade** [comment]
> Sollte doch dem vom REDAXO entsprechen? Oder ist hier was, was ich übersehe?

Siehe https://github.com/FriendsOfREDAXO/focuspoint/issues/83#issuecomment-582306805

**Comment by skerbis** [comment]
danke
