### ISSUE TITLE
Als Nicht-Admin verschieben sich die Button

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/quick_navigation#123]
Wenn man die Ansicht für einen anderen User simuliert, verschiebt sich die Ansicht der Quick-Navi (ich weiss nicht, ob es beim eigentlichen User dann auch so ist.)

![Bildschirmfoto 2020-10-19 um 18 08 26](https://user-images.githubusercontent.com/16903055/96477002-47f98180-1236-11eb-9b9e-696e04b2fd11.png)

**Comment by skerbis** [comment]
Kann ich nicht bestätigen
