### ISSUE TITLE
"Voriger / Nächster" ausblenden wenn keine Artikel vorhanden

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/quick_navigation#126]
Gibt es eine Möglichkeit das "Voriger / Nächster" für Kategorien auszublenden wenn es keine Artikel darunter gibt? 
Bei 99 % aller Projekte sind da zwei Knopfe die nicht nutzbar sind ;) 

Alternativ könnte man das per Konfig einstellen, ob auf Artikel innerhalb einer Kategorie oder auf die Kategorien innerhalb der Struktur das "Voriger / Nächster" anwendbar ist.

**Comment by skerbis** [comment]
PR welcome

**Comment by skerbis** [comment]
@rkemmere ich habe die Pfeile stehen lassen damit es nicht so ein "Gezappel" ist.

**Comment by rkemmere** [comment]
Sehe schon das es bei dem ein oder anderen Sinn macht, das zu nutzen. Dann vielleicht echt nur die Konfig ob "Artikelnavigation" ja / nein.

**Comment by skerbis** [comment]
per user setting gerne :-)

**Comment by skerbis** [comment]
Kann der User jetzt selbst entscheiden.
