### ISSUE TITLE
ReferenceError: Can't find variable: rex_searchfield_init

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#133]
Datei quicknavi.js in Zeile 13 wird gemeckert.

Der Fehler erscheint, sobald man das Dropdown zur Modulauswahl anklickt.

**Comment by skerbis** [comment]
bitte etwas genauer erklären. Ich sehe den Fehler nicht.

**Comment by tbaddade** [comment]
> bitte etwas genauer erklären.

Kann ich leider nicht mehr.
