### ISSUE TITLE
Call to undefined method rex_yform_manager_table::getCSRFKey()

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/quick_navigation#134]
Die Methode gibt's im aktuelle YForm Release nicht. 

<details>
<summary>System report (REDAXO 5.12.1, PHP 7.4.20, MySQL 5.7.33)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.20     |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.33 |
| Character set | utf8         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/89.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |

| Packages          |            |
| ----------------: | :--------- |
|           adminer | 1.9.0      |
|            backup | 2.7.1      |
|       be_password | 2.0.0      |
|          be_style | 2.12.1     |
|   be_style/redaxo | 2.12.1     |
|           bloecks | 3.0.2      |
|  bloecks/cutncopy | 3.0.2      |
|    bloecks/status | 3.0.2      |
|        focuspoint | 3.0.2      |
|           install | 2.9.1      |
|        iw_backend | 1.0        |
|          markitup | 3.6.1      |
|            mblock | 3.2.0      |
|     media_manager | 2.11.1     |
|         mediapool | 2.10.1     |
|          metainfo | 2.8.1      |
|             mform | 6.0.9      |
|         phpmailer | 2.10.2     |
|  quick_navigation | 5.1.0      |
|             sprog | 1.2.0      |
|         structure | 2.12.1     |
| structure/content | 2.12.0     |
|             theme | 1.3.3      |
|          uploader | 2.2.2      |
|               url | 1.0.1      |
|         useragent | 2.3.0      |
|             users | 2.8.0      |
|            watson | 2.2.0      |
|             yform | 3.4.2      |
|       yform/email | 3.4.2      |
|     yform/manager | 3.4.2      |
|   yform_usability | 1.4        |
|          yrewrite | 2.7        |

</details>

**Comment by ynamite** [comment]
Statt:
`$_csrf_key = $table->getCSRFKey();`
funktioniert:
`$_csrf_key = 'table_field-'.$table->getTableName();`

**Comment by skerbis** [comment]
Jupp .. die Methode kam wohl auch erst mit 4.x.
