### ISSUE TITLE
QuickNavigation wird wegen Error nicht angezeigt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#136]
**Error:** Call to a member function hasPerm() on null
**File:** src/addons/quick_navigation/lib/QuickNavigation.php
**Line:** 484

<details>
<summary>Stacktrace</summary>

| Function                                | File                                                           | Line     |
| --------------------------------------- | -------------------------------------------------------------- | -------- |
| QuickNavigation::get_yformtables        | src/addons/quick_navigation/lib/QuickNavigation.php            | 593      |
| QuickNavigation::get                    | src/addons/quick_navigation/lib/api_quicknavigation_render.php | 7        |
| rex_api_quicknavigation_render->execute | src/core/lib/api_function.php                                  | 180      |
| rex_api_function::handleCall            | src/core/backend.php                                           | 229      |
| require                                 | src/core/boot.php                                              | 141      |
| require                                 | public/redaxo/index.php                                        | 12       |

</details>
<details>
<summary>System report (REDAXO 5.12.1, PHP 7.4.25, MariaDB 10.5.9)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.1     |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.0 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages          |             |
| ----------------: | :---------- |
|  quick_navigation | 5.2.0       |
|             yform | 4.0.0-dev2  |
|       yform/email | 4.0.0-dev   |
|     yform/manager | 4.0.0-dev   |

</details>

**Comment by skerbis** [comment]
Bitte mit der Beta testen , nicht mit dev. Dann sollte es gehen

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/commit/3b7ee0d8d8a94c16a15d6ddbf8b487dac7347c4c

**Comment by tbaddade** [comment]
> Bitte mit der Beta testen , nicht mit dev. Dann sollte es gehen

Meinst du YForm? Da verwende ich die aktuelle GH Version.

**Comment by skerbis** [comment]
nein quick navi

**Comment by skerbis** [comment]
eben und die ist -dev Quicknavi sucht nach einer Beta. 
Fix ist raus und im Installer.
