### ISSUE TITLE
QN verliert den aktiven Zustand

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#138]
QN verliert den aktiven Zustand, wenn in der Sidebar eines Artikels die Formulare von YRewrite oder YCom aktualisiert werden.

**Comment by skerbis** [comment]
Ja das kann sein. Weil dies eigene PJAX Container sind.

**Comment by skerbis** [comment]
Getestet. Sehe das Problem hier nicht: 
<img width="534" alt="Bildschirmfoto 2022-01-19 um 17 53 31" src="https://user-images.githubusercontent.com/791247/150177240-a21aa65a-89ed-415f-aa77-99c6827cb61f.png">

**Comment by tbaddade** [comment]
> Getestet. Sehe das Problem hier nicht:

Metadaten klappt. Ich meine Die Container von YRewrite oder YCom weiter unten.

**Comment by skerbis** [comment]
Da passt es auch bei mir

**Comment by tbaddade** [comment]
Verschieb mal den Artikel in eine andere Kategorie. Wie sieht es dann aus?

**Comment by skerbis** [comment]
Status bleibt erhalten

**Comment by skerbis** [comment]
Greift da was bei dir evtl in die api rein?

**Comment by skerbis** [comment]
Ich verliere nur den Status (aber nicht immer) wenn ich zwischen arbeits und live Version mal umschalte - gerade getestet

**Comment by tbaddade** [comment]
Ich hab es eben wieder gehabt. Diesmal direkt beim Umwandeln von Kategorie zu Artikel unter dem Tab "Funktionen".

<img width="1265" alt="Bildschirmfoto 2022-01-25 um 10 08 48" src="https://user-images.githubusercontent.com/338267/150946621-21cfca93-7374-42e5-84a9-3d6b39c39b2b.png">

**Comment by skerbis** [comment]
@tbaddade welcher Browser?  
Ich hab's eben wieder getestet, hier Safari. 
Quicknavi übernimmt ja die Daten aus der übergebenen URL. 
Werden evtl. Parameter nicht übergeben?

**Comment by skerbis** [comment]
Ah moment ... 
Beim Umwandeln einer Kategorie ist die resultierende URL falsch. Da steht dann danach immer noch die alte Kategorie in der URL. Quicknavi kann folglich die Kategorie nicht ermitteln.

**Comment by skerbis** [comment]
@tbaddade hier müsste überprüft werden ob die übergebene Category existiert. Wenn nicht müsste diese anhand der Artikel-ID neu ermittelt werden. 

https://github.com/FriendsOfREDAXO/quick_navigation/blob/a84be839ba93680197d372b38b59e2087c54f775/lib/QuickNavigation.php#L59

**Comment by tbaddade** [comment]
Noch ein Fall: 

1. Slice im Artikel hinzugefügt. 
2. Reload via `cmd+r`. 
3. Aktiver Zustand geht verloren (Homepage wird angezeigt).

**Comment by skerbis** [comment]
@tbaddade 
Jupp weil Beim slice editieren keine Kategorie mitgegeben wird: 
/redaxo/index.php?page=content/edit&article_id=1&slice_id=2&ctype=1&clang=1&function=edit#slice2

**Comment by tbaddade** [comment]
> Jupp weil beim slice editieren keine Kategorie mitgegeben wird:

Die ließe sich aus der `article_id` holen.

**Comment by skerbis** [comment]
Ja das habe ich vor. Bitte nicht ein wenig Geduld.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/commit/4372f9bcc8420effc153a5706c9b38b636b799d1

**Comment by tbaddade** [comment]
Getestet. Danke 👍

**Comment by skerbis** [comment]
Release ist unterwegs
