### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/quick_navigation#14]
Könnte die SN nicht in die Leiste?

Oder zumindest daneben...

![sn](https://cloud.githubusercontent.com/assets/330516/22462133/535697e2-e7ac-11e6-9bdd-7b4f149981c5.png)

**Comment by skerbis** [comment]
gibt es dafür einen EP?

**Comment by tbaddade** [comment]
aktuell wäre die Schnellnavi immer an derselben Stelle. Egal auf welche Seite man ich befindet.
