### ISSUE TITLE
Nach Update via Installer `Call to undefined method Watson\Foundation\Watson::getToggleButton()`

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/quick_navigation#145]
<html>
<body>

11.11.2022, 15:19:21 | Info | AddOn watson updated from 2.3.0-beta1 to version 2.3.0 |   |  
-- | -- | -- | -- | --
11.11.2022, 15:18:51 | Error | Call to undefined method Watson\Foundation\Watson::getToggleButton() | redaxo/src/addons/quick_navigation/lib/QuickNavigation.php | 553
11.11.2022, 15:18:50 | Error | Call to undefined method Watson\Foundation\Watson::getToggleButton() | redaxo/src/addons/quick_navigation/lib/QuickNavigation.php | 553
11.11.2022, 15:18:49 | Error | Call to undefined method Watson\Foundation\Watson::getToggleButton() | redaxo/src/addons/quick_navigation/lib/QuickNavigation.php | 553
11.11.2022, 15:18:43 | Error | Call to undefined method Watson\Foundation\Watson::getToggleButton() | redaxo/src/addons/quick_navigation/lib/QuickNavigation.php | 553

</body>
</html>11.11.2022, 15:19:21	
Info
AddOn watson updated from 2.3.0-beta1 to version 2.3.0
11.11.2022, 15:18:51	
Error
Call to undefined method Watson\Foundation\Watson::getToggleButton()
[redaxo/src/addons/quick_navigation/lib/QuickNavigation.php](vscode://file//home/users/kulturkeller/www/kulturkeller.de/www/redaxo/src/addons/quick_navigation/lib/QuickNavigation.php:553)
553
11.11.2022, 15:18:50	
Error
Call to undefined method Watson\Foundation\Watson::getToggleButton()
[redaxo/src/addons/quick_navigation/lib/QuickNavigation.php](vscode://file//home/users/kulturkeller/www/kulturkeller.de/www/redaxo/src/addons/quick_navigation/lib/QuickNavigation.php:553)
553
11.11.2022, 15:18:49	
Error
Call to undefined method Watson\Foundation\Watson::getToggleButton()
[redaxo/src/addons/quick_navigation/lib/QuickNavigation.php](vscode://file//home/users/kulturkeller/www/kulturkeller.de/www/redaxo/src/addons/quick_navigation/lib/QuickNavigation.php:553)
553
11.11.2022, 15:18:43	
Error
Call to undefined method Watson\Foundation\Watson::getToggleButton()
[redaxo/src/addons/quick_navigation/lib/QuickNavigation.php](vscode://file//home/users/kulturkeller/www/kulturkeller.de/www/redaxo/src/addons/quick_navigation/lib/QuickNavigation.php:553)
553

**Comment by skerbis** [comment]
hmm hätte aber da sein müssen da bereits in der beta auch vorhanden

**Comment by tbaddade** [comment]
> hätte aber da sein müssen da bereits in der beta auch vorhanden

das stimmt nicht. In der 2.3.0-beta1 war die Methode noch nicht vorhanden.

**Comment by skerbis** [comment]
fixed
