### ISSUE TITLE
quick_navigation erzeugt bei jedem backend request eine Abfrage

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/quick_navigation#147]
Ist mir aufgefallen, als ich mir die backend user logs angesehen habe und immer 2 Aufrufe pro request hatte. Ist dieser request immer direkt nötig?

**Comment by skerbis** [comment]
Quicknavi aktualisiert sich per API/Ajax um den aktuellen Pfad zu ermitteln und das Menu zu rendern. Ohne diese Lösung würde es größere performance Probleme geben, gerade bei großen strukturen

**Comment by skerbis** [comment]
Kannst du diese requests filtern?

**Comment by dergel** [comment]
> Kannst du diese requests filtern?

könnte ich .. aber wäre nicht richtig, wenn ich backendzugriffe loggen will. weiss gerade auch keine Lösung. Die Navigation zu rendern wenn man draufklickt ist wahrscheinlich nicht so schön.

**Comment by skerbis** [comment]
Vielleicht könne man hier einen Parameter mitgeben, der deinem Script mitteilt, hey das musst du nicht loggen. 
Oder was wäre wenn es einen Nutzer "root" gäbe unter dem sowas ausgeführt würde? Vielleicht brauchen wir sowas in REDAXO.

**Comment by dergel** [comment]
Es geht ja eher darum, dass man nachvollziehen kann was passiert und das nicht deaktivieren kann. Deswegen wäre so ein flag meiner Meinung nach nicht richtig. Ich frage mal dreist - muss das ein API Call sein?

**Comment by skerbis** [comment]
ja

**Comment by skerbis** [comment]
Wir haben mit @staabm den API call eingeführt da  die Quicknavi sonst für Performanceprobleme gesorgt hatte.

**Comment by dergel** [comment]
stimmt schon. dafür ist so ein call ja auch da.. Ich ziehe mein Issue zurück :)
