### ISSUE TITLE
Begriff Schnellnavigation weglassen?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#15]
Soll der Begriff bleiben, oder einfach nur die aktuell gewählte Kategorie gezeigt werden?
Stattdessen, evtl. ein Icon?

**Comment by olien** [comment]
Ich würde es ersatzlos streichen und immer die aktuelle Kategorie zeigen.

**Comment by skerbis** [comment]
Wird in 0.3.0 entfernt
