### ISSUE TITLE
Id-Feld optional anzeigen?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#16]

**Comment by skerbis** [comment]
Ja kommt in die Settings , die würde ich gerne in system unterbringen

**Comment by skerbis** [comment]
Alternativ über ein Recht aktivieren?

**Comment by skerbis** [comment]
@tbaddade ist als Recht einblendbar

**Comment by skerbis** [comment]
Settings kommen später
