### ISSUE TITLE
Während des Updates: Class "rex_api_quicknavigation_render" not found

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#165]
**Description / Beschreibung**

Beim Update von 6.1.0 auf 7.0.4 erscheint diese Meldung

**Did it whoops? / Whoops erhalten?**

**Error:** Class "rex_api_quicknavigation_render" not found
**File:** src/addons/quick_navigation/boot.php
**Line:** 34

<details>
<summary>Stacktrace</summary>

| Function                              | File                               | Line     |
| ------------------------------------- | ---------------------------------- | -------- |
| rex_package->{closure}                | src/core/lib/extension.php         | 52       |
| rex_extension::{closure}              | src/core/lib/util/timer.php        | 62       |
| rex_timer::measure                    | src/core/lib/extension.php         | 42       |
| rex_extension::registerPoint          | src/core/lib/view.php              | 322      |
| rex_view::title                       | src/addons/install/pages/index.php | 5        |
| require                               | src/core/lib/packages/package.php  | 233      |
| rex_package->includeFile              | src/core/lib/be/controller.php     | 508      |
| rex_be_controller::{closure}          | src/core/lib/util/timer.php        | 62       |
| rex_timer::measure                    | src/core/lib/be/controller.php     | 490      |
| rex_be_controller::includePath        | src/core/lib/be/controller.php     | 439      |
| rex_be_controller::includeCurrentPage | src/core/backend.php               | 253      |
| require                               | src/core/boot.php                  | 157      |
| require                               | public/redaxo/index.php            | 12       |

</details>
<details>
<summary>System report (REDAXO 5.17.1, PHP 8.3.1, MariaDB 11.2.2)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.17.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.3.1      |
|       OPcache | yes        |
|        Xdebug | yes        |

| Database      |                |
| ------------: | :------------- |
|       Version | MariaDB 11.2.2 |
| Character set | utf8mb4        |
</details>

**Comment by skerbis** [comment]
Ne idee wie ich das verhindern kann die Class mit dieser Bezeichnung existiert nicht mehr.

**Comment by tbaddade** [comment]
> Ne idee wie ich das verhindern kann 

Habe mir das nicht weiter angesehen, aber man könnte den alten Klassennamen noch mit nehmen und als deprecated kennzeichnen.

**Comment by skerbis** [comment]
hmm, genau das wollte ich eigentlich nicht.

**Comment by skerbis** [comment]
ich nehm die alten classes erstmal mit
