### ISSUE TITLE
Dropdownliste ist so breit wie der längste Artikelname

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/quick_navigation#17]
Diese Eigenschaft, führt bei einem Projekt, bei dem ein Kunde einen extrem langen Artikelnamen (was natürlich auch ungünstig ist) vergeben hat dazu, das die Liste links aus dem Viewport läuft.
Version 0.1.5

**Comment by skerbis** [comment]
Soll ich die Artikelnamen ab einer bestimmten Länge kürzen? Oder würdest du ein Scrollen bevorzugen?

**Comment by isospin** [comment]
Kürzen finde ich gut!

**Comment by tbaddade** [comment]
den kompletten Name könnte man ggf. im title Attribute unterbringen

**Comment by skerbis** [comment]
Das Menü hat jetzt a) eine maximale Breite, b) die Links werden gekürzt, c) Title-Attribute wurden hinzugefügt. Gerne bitte Github-Version testen.

**Comment by isospin** [comment]
top! 
funktioniert und sieht gut aus
