### ISSUE TITLE
Artikel anzeigen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/quick_navigation#18]
Schön wäre es wenn Artikel (ausser Startartikel?) wahlweise angezeigt werden könnten.

**Comment by skerbis** [comment]
Kommt auf die Größe der Webpräsenz an. Wenn man z.B. sehr viele Newsartikel hat, will man die ja nicht alle mitschleppen. Ich würde es als Kategorie-Sprung-Menü belassen.

**Comment by tbaddade** [comment]
Das fehlte mir auch wusste aber nicht wie man das am sinnvollsten in die Liste reinholt.

Bisherige Idee war, dass man unterhalb der Kategorie 2 Tabs hätte, so dass man zwischen den Kindkategorien und Artikel wechseln kann.

Ähnlich wie bei GH bei der Auswahl der Branches. Tabs: Branches / Tags, nur müsste das unter jeder Kategorie die mehr als den Startartikel hat.

**Comment by olien** [comment]
Ich würde die etwas eingerückt darstellen wenn das geht (kursiv / kleiner?).
Bei der Rechtevergabe könntest Du ja noch hinzufügen ob Artikel angezeigt werden sollen oder nicht.

**Comment by skerbis** [comment]
Ihr wünscht euch eine komplette Navi mit allen Unterpunkten? Die gibt es bereits. Treestructure. Diese als Off-Canvas-Sidebar würde den Wunsch erfüllen.

**Comment by olien** [comment]
okok. Ich mach hier zu :-)
