### ISSUE TITLE
UX: favoriten verwaltung aus favoriten overlay verlinken

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/quick_navigation#180]
**Feature description / Feature Beschreibung**

damit der user einfacher findet wie man favoriten pflegt, wäre es nützlich wenn im overlay ein link enthalten mit dem man zur verwaltung springt

![grafik](https://github.com/FriendsOfREDAXO/quick_navigation/assets/120441/5f529dc0-3024-416b-a4c5-366bac6bdc1e)

**Comment by skerbis** [comment]
Ich habe das alte Verhalten wieder hergestellt. Favoriten werden erst angezeigt wenn vorhanden.

**Comment by tbaddade** [comment]
> Ich habe das alte Verhalten wieder hergestellt. Favoriten werden erst angezeigt wenn vorhanden.

Ich hatte nicht mit bekommen, dass man überhaupt welche pflegen kann. 
Hatte den Button deshalb immer anzeigen lassen und finde den Vorschlag mit der Verlinkung von @staabm recht sinnvoll.

**Comment by skerbis** [comment]
Ich hätte gerne eine viel flexiblere Lösung für Favoriten. Nicht nur Kategorien…
