### ISSUE TITLE
Favoriten

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/quick_navigation#182]
**Feature description / Feature Beschreibung**

Nur anzeigen wenn welche vorhanden?

Dark Mode pass nicht

![image](https://github.com/FriendsOfREDAXO/quick_navigation/assets/330516/69022457-18e0-458a-b591-8df364a36177)

**Comment by skerbis** [comment]
passend dazu: https://github.com/FriendsOfREDAXO/quick_navigation/issues/180
