### ISSUE TITLE
Zuletzt bearbeitete Artikel auflisten / Dropdown / Tab 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#19]

**Comment by tbaddade** [comment]
Oder in ein Dropdown wie hier bei GH mit der Branchauswahl (Branches / Tags). Das spart Platz.

**Comment by skerbis** [comment]
Du meinst als Tab?

**Comment by skerbis** [comment]
Habe eine Artikel-History hinzugefügt - mag wer testen?

**Comment by skerbis** [comment]
Ist aktuell für Admins und "Chefredakteure" gedacht, es wird nicht nach Kategorie-Benutzerrechten gecheckt.

**Comment by tbaddade** [comment]
> Ist aktuell für Admins und "Chefredakteure" gedacht, es wird nicht nach Kategorie-Benutzerrechten gecheckt.

Könntest das abfragen
https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Workflows/Structure/ArticleSearch.php#L167

**Comment by skerbis** [comment]
würde das den Aufruf nicht verlangsamen? Wie wäre es wenn "normale" User nur Ihre eigenen Artikel sehen würden, die sie bearbeitet haben. Admins und Leute mit entsprechendem Recht sehen die Änderungen aller User?
