### ISSUE TITLE
Eine Schnellsuche wie bei select2 wäre nützlich

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#2]
Gerade bei umfangreichen Seiten würde diese sehr schnell zum Ziel führen. 
https://github.com/select2/select2

**Comment by isospin** [comment]
+1

**Comment by skerbis** [comment]
Watson https://github.com/tbaddade/redaxo_watson

**Comment by skerbis** [comment]
Ist in aktueller Github-Fassung integriert.
