### ISSUE TITLE
Notice Hinweise im Systemlog

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/quick_navigation#24]
Seit dem letzten Update (mit grandiosen neuen Features, danke dafür), wird leider der Systemlog mit Notice Hinweisen geflutet - vielleicht kann sich das kurz jemand anschaun, ist sicher nur eine Kleinigkeit.

`07.02.2017 10:07:02	Notice	Undefined variable: link	
redaxo/src/addons/quick_navigation/lib/QuickNavigation.php
49`

Dankeschön!

**Comment by skerbis** [comment]
schon korrigiert. Wird heute released.

**Comment by georgkaser** [comment]
Grazie! :)
