### ISSUE TITLE
Letzte / Neuste Medien

### ISSUE THREAD

**Issue by ghost** [FriendsOfREDAXO/quick_navigation#25]
Das wäre eine tolle Erweiterung. Dann wären alle Funktionen des Dashboards da. 
Tipp zum Thema: http://www.redaxo.org/de/forum/module-aktionen-f44/erledigt-neueste-dateien-im-medienpool-t21369.html

**Comment by skerbis** [comment]
Ist in Arbeit

**Comment by skerbis** [comment]
ghost?

**Comment by skerbis** [comment]
erledigt
