### ISSUE TITLE
Spalte geht verloren

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/quick_navigation#28]
Wenn man Artikelinhalte in einer bestimmte Template-Spalte bearbeitet und dann über die quick navigation die Seite wechselt, landet man nicht in derselben Spalte. Das war bei der Version für R4 der Fall und fand ich ganz praktisch.

**Comment by skerbis** [comment]
hmm, ich dachte aufgrund von PJAX funktionier   `$droplistContext->setParam('ctype', rex_request('ctype', 'int')); ` nicht. Kann hier jemand helfen?

**Comment by gharlan** [comment]
Zu beachten ist hier übrigens: Ctype X kann im anderen Artikel was ganz anderes sein, oder auch gar nicht existieren, wenn der Artikel ein anderes Template hat.
Weiß gerade nicht passiert, wenn man einen Artikel mit einer dort nicht existenten ctype id aufruft.

**Comment by skerbis** [comment]
Man landet im 1. CTYPE. Das Verhalten ist soweit wie gewünscht.

**Comment by skerbis** [comment]
Der Hinweis mit den unterschiedlichen Templates ist gut.  @gharlan 
Es bleibt wie es ist.

**Comment by ynamite** [comment]
wontfix fände ich schade ... wie gesagt, man landet ja in dem Fall eh im ersten CTYPE, wieso also wontfix?

**Comment by tbaddade** [comment]
Problem ist, dass beim ersten Aufruf des Content der Ctype in der Url nicht mitgegeben wird.

Daher hat der [context hier](https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_feldtypen.md#datetime) schon einmal initial gar kein ctype Parameter.

Beim Wechsel von Ctype zu Ctype klappt es nicht, wegen dem pjax. Die Url wird angepasst, aber Quicknavigation greift diese nicht ab. @gharlan gab es für das Verhalten nicht bereits eine Lösung?

**Comment by skerbis** [comment]
@ynamite 
1) Wenn du in der Struktur navigierst, merkt sich das System auch nicht den Ctype. 
2) Die Quick Navigation müsste sich nach jedem Wechsel der Ctypes neu generieren? Oder die Urls im Menü manipulieren.

**Comment by ynamite** [comment]
@skerbis 

wie gesagt, in R4 ging's halt und fand's persönlich halt benutzerfreundlicher. Hatte gerade denn fall, das ich auf mehreren Seiten im 2. CTYPE etwas ändern musste und das ging in R4 deutlich flotter. 

Falls es zu aufwendig ist dann halb so wild, aber wär schon schön ;)

**Comment by skerbis** [comment]
Ich lasse es mal offen. Evtl. hat jemand eine zündende Idee.

**Comment by skerbis** [comment]
@ynamite, @tbaddade  bitte testen: https://github.com/FriendsOfREDAXO/quick_navigation/pull/29

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/commit/b13630e73ba132cc87240fee6e10f5b99318a150#diff-32bb636196f91ed59d7a49190e26b42c
