### ISSUE TITLE
wird auf Metadaten/Funktionen Seite nicht angezeigt

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/quick_navigation#3]
Die QuickNavi ist nur im Editiermodus sichtbar. In den Metadaten und Funktionen verschwindet sie wieder. Dort wäre sie aber auch sehr nützlich.

**Comment by eaCe** [comment]
immer anzeigen ist ja ganz gut, nur funktioniert sie von anderen seiten aus nicht? ist das nur bei mir so?

**Comment by tbaddade** [comment]
@eaCe Ist in der Version 0.1.1 korrigiert. Danke Dir.

**Comment by isospin** [comment]
super! vielen dank.
mir ist gerade noch aufgefallen, das sie jetzt auch im medienpool angezeigt wird

**Comment by tbaddade** [comment]
> mir ist gerade noch aufgefallen, das sie jetzt auch im medienpool angezeigt wird

@isospin Sollte jetzt nicht mehr erscheinen.

@eaCe Auch der Login sollte wieder funktionieren
