### ISSUE TITLE
alert-DIV bleibt beim Seitenwechsel sichtbar

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/quick_navigation#32]
Nicht wirklich ein Problem, nur eben aufgefallen und sieht bisschen komisch aus:

Wenn man zBsp. eine neue Unterkategorie hinzufügt, wird oben eine Statusmeldung angezeigt, etwa so
```<div class="alert alert-success">Kategoriestatus wurde aktualisiert!</div>```

Wechselt man danach per quick_navigation die Seite, bleibt diese Statusmeldung stehen bzw. wird beim laden der neuen Inhalte nicht wieder verborgen.

**Comment by skerbis** [comment]
Ja, das liegt an PJAX.

**Comment by ynamite** [comment]
Bist du dir sicher? Wieso wird bei einem Seitenwechsel das komplette HTML (inkl. Skripts etc.) neu geladen und nicht nur der relevante Inhalt? In der package.yml steht auch nix von PJAX.

**Comment by skerbis** [comment]
Ich denke, da funkt ein anderes Addon dazwischen.

**Comment by ynamite** [comment]
https://github.com/tbaddade/redaxo_sprog/issues/36
