### ISSUE TITLE
Beim Seitenwechsel landet man in der Eingabemaske des zuvor gespeicherten Blocks

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/quick_navigation#33]
Wenn man in einer Kategorie einen Block bearbeitet und gespeichert hat und direkt im Anschluss per Quick Navigation die Seite wechselt, landet man in der Ziel Kategorie direkt in der Eingabemaske des zuvor editierten Blocks.

zT. ganz praktisch, wenn man in mehreren Kategorien dasselbe Modul einbauen will, aber wahrscheinlich ungewollt.

**Comment by skerbis** [comment]
Kann ich nicht reproduzieren.

**Comment by skerbis** [comment]
@ynamite hat sich das erledigt?

**Comment by ynamite** [comment]
Yep, kann weg. Kann's auch nicht mehr reproduzieren.
