### ISSUE TITLE
.focus() auf Search-Input ("Filter")

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/quick_navigation#34]

**Comment by skerbis** [comment]
ohne js: 
https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/fragments/quick_drop.php#L42

**Comment by Hirbod** [comment]
Funzt so vermutlich nicht auf dem iPhone, müsste man testen

**Comment by skerbis** [comment]
Stimmt, allerdings nervt es, wenn die Tastatur sofort eingeblendet wird auf einem mobilen Gerät und man noch nicht erfasst hat was man man sieht.

**Comment by skerbis** [comment]
scrolling gerade gefixt ;-) - Ich bleibe bei der HTML5 autofocus Lösung. Primäre Funktion ist das Menü, nicht der Filter.

**Comment by skerbis** [comment]
iOS erlaubt auch kein .focus()... gerade getestet

**Comment by Hirbod** [comment]
Doch, wenn die Aktion einem Touch / Click vorausgeht schon

**Comment by skerbis** [comment]
wie ist es unter Android?

**Comment by Hirbod** [comment]
Ähnlich wenn ich nicht irre

**Comment by Hirbod** [comment]
Aber ich find es auch nicht schlimm wenn es auf dem Smartphone nicht fokussiert

**Comment by Hirbod** [comment]
Hab dein Update getestet, `autofocus` funktioniert gar nicht (da das Input ja versteckt ist und beim öffnet gar kein trigger dazu mehr ausgelöst wird). Ich glaube, hier kommt man gar nicht an der JS-Variante rum

**Comment by skerbis** [comment]
also im safari geht's

**Comment by Hirbod** [comment]
Firefox nicht

**Comment by skerbis** [comment]
bitte testen:
https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/assets/quicknavi.js

**Comment by skerbis** [comment]
@Hirbod

**Comment by Hirbod** [comment]
passt
