### ISSUE TITLE
BEER-WARE License

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#36]
Falls du die Lizenz noch dabei hast, weil ich die am Anfang mit drin hatte, kannst die auch gern löschen. Für mich gehört die nicht in eine Extradatei sondern in die `LICENSE.md` Datei. So geht das nur unter.

**Comment by skerbis** [comment]
Schade, ich fand es ganz nett. Kann man es zusätzlich in die License.md packen als alternative Lizenz?

**Comment by schuer** [comment]
@skerbis Wenn du Beerware mit in die LICENSE.md steckst, erkennt GitHub die Lizenz nicht mehr sauber, siehe https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/issues/15#issuecomment-270662360

**Comment by tbaddade** [comment]
>  Wenn du Beerware mit in die LICENSE.md steckst, erkennt GitHub die Lizenz nicht mehr sauber

was kein Beinbruch wäre.

**Comment by skerbis** [comment]
Daumen hoch wenn's wieder rein soll
