### ISSUE TITLE
Idee: Watson-Button darstellen, wenn Watson installiert?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#37]
![bildschirmfoto 2017-07-31 um 10 34 20](https://user-images.githubusercontent.com/791247/28769443-d719ed64-75db-11e7-9b4a-b8fbbef9f054.png)

Automatisch oder auf Wunsch? 
Bei auf Wunsch benötigt man natürlich ne Settingsseite - aber wohin damit? Extra einen Menüpunkt für QuickNavigation finde ich blöd.

**Comment by tbaddade** [comment]
Der Button erscheint bereits, wenn im Watson die Einstellung dazu gewählt wurde.

**Comment by skerbis** [comment]
@tbaddade es geht darum den Button direkt in der QuickNavigation-Leiste darzustellen. Das passt doch schön zusammen - oder nicht? Siehe Screenshot.

**Comment by tbaddade** [comment]
Kannst du ja gern machen. Du müsste dann den Button aus dem Header löschen oder dies wird dann doppelt dargestellt.

> Bei auf Wunsch benötigt man natürlich ne Settingsseite

Brauchst du nicht. Du kannst ja die gewählte Einstellung vom Watson holen. [Siehe hier](https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Foundation/Watson.php#L21-L24)

**Comment by skerbis** [comment]
Alternative: du benutzt den gleichen EP. Sonst müsste ich auch noch die Watson Rechte prüfen.

**Comment by tbaddade** [comment]
Dann müsste ich auf QN prüfen. Der Watson würde sich da so allein vorkommen, wenn die QN nicht installiert ist ;). Ich vermute aber auch, dass es damit nicht getan ist wenn der Button an der Stelle gleich ausgegeben wird.

**Comment by skerbis** [comment]
ok ... ich blende den default Watson Button nun per CSS aus.
