### ISSUE TITLE
Aktives Element mittig im Dropdown anzeigen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#38]

**Comment by skerbis** [comment]
Wenn du auf den Focus in der Suche verzichten kannst, kein Problem. @tbaddade

**Comment by tbaddade** [comment]
@skerbis ich meine eher, dass die Scrollposition des Dropdown angepasst wird.

**Comment by skerbis** [comment]
Ja das geht hiermit. Dann verschwindet jedoch die Suche, die müsste man dann fixieren. 

```
$(document).on("shown.bs.dropdown", function() {
   $(this).find(".dropdown-menu li.active a").focus()
});
```

**Comment by skerbis** [comment]
@tbaddade bitte aktuelle Github-Version testen

**Comment by skerbis** [comment]
Suche bleibt im Drop-Down nicht oben fixiert stehen. ...

**Comment by tbaddade** [comment]
Passt soweit, außer dass die Suche rechts unterhalb der Scrollbar ist.

**Comment by skerbis** [comment]
Das Such-Feld bleibt nicht fest, wenn man die Seite Scrollt.

**Comment by skerbis** [comment]
@tbaddade die Suche ist jetzt fixiert, allerdings musste ich ein 2. UL einsetzen, was dazu führt, dass der redaxo-eigene Stil nicht mehr funktioniert für die Links.

**Comment by tbaddade** [comment]
> was dazu führt, dass der redaxo-eigene Stil nicht mehr funktioniert für die Links.

Finde ich nicht weiter schlimm. Würde die Listitems sogar eher weiter zusammenziehen.

**Comment by skerbis** [comment]
Das ist der Effekt unter Edge .. ich muss noch checken, warum das da so aussieht. 
Werde die CSS noch weiter bearbeiten .. bin noch nicht zufrieden.

**Comment by tbaddade** [comment]
Du könntest sass verwenden, dann hast immer die primary Farbe auch der anderen Themes.

**Comment by skerbis** [comment]
Wie komme ich denn mit SASS an die Daten des Themes? Jetzt muss er mir aber was beibringen ;-)

**Comment by tbaddade** [comment]
Schau dir mal das redaxo Plugin im be_style AddOn an. Das wäre eine Variante. Aber vermutlich wäre das hier dann doch ein wenig übertrieben :)

**Comment by skerbis** [comment]
für eine Farbe doch ein wenig viel Aufwand.

**Comment by skerbis** [comment]
Im nächsten Release
