### ISSUE TITLE
Watson Button wird nicht angezeigt

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/quick_navigation#39]
Beide Addons sind aktuell (Installer)

**Comment by skerbis** [comment]
Ist in den Watson-Einstellungen der Button altiviert?
![bildschirmfoto 2017-08-09 um 09 16 11](https://user-images.githubusercontent.com/791247/29109490-732b2ff2-7ce3-11e7-8abf-bf9106661052.png)

**Comment by olien** [comment]
Natürlich nicht :-)
Funktioniert (Selbstverständlich. Wie konnte ich zweifeln...)
