### ISSUE TITLE
Eigene Schnellnavi zusammensetzen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#4]
Damit man ggf. schnell in YForm Tabellen oder andere AddOnseiten springen kann.

**Comment by skerbis** [comment]
Ist doch eher was für ein Dashboard - oder?

**Comment by tbaddade** [comment]
Die Schnellnavi ist ja auf allen Seiten vorhanden. So müsste man erst zum Dashboard und dann geht weiter.

**Comment by skerbis** [comment]
Toll wäre wenn das über das normale Menü gelöst werden könnte.

**Comment by skerbis** [comment]
Da brauche ich wohl erstmal eine Lösung um z.B. yform Tabellen zu pickern

**Comment by skerbis** [comment]
Ich denke, das ist ein Feature für das reguläre Menü. Die Quick Navigation sollte sich auf die Struktur beschränken.

**Comment by skerbis** [comment]
Da keine Einwände kommen, schließe ich das hier.
