### ISSUE TITLE
Feature: Accesskey für Kategorie Dropdown

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/quick_navigation#41]
Mit einem Accesskey fürs Kategoriedropdown wäre die Struktur wieselflink über die Tastatur navigierbar. https://github.com/FriendsOfREDAXO/quick_navigation/pull/40/files
Ich hab als Accesskey `q` für quick_navigation genommen.  Tuts in Chrome auf Windows astrein - man müsste halt nur gucken ob der Projekt Lead `q` mag/ obs auch überall sonst funktioniert.
Ist auf jeden Fall saupraktisch :)

**Comment by skerbis** [comment]
q steht für mich irgendwie für quit

**Comment by schuer** [comment]
`l` für location

mit cmd/strg = l springt man ja in die browseradresszeile, es geht also um navigation. vielleicht passt das dann thematisch mit der quick navigation?

**Comment by skerbis** [comment]
es wird m
