### ISSUE TITLE
Feature-Wunsch: Quick Navigation auch in der Linkmap verfügbar machen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/quick_navigation#42]

**Comment by skerbis** [comment]
Wei meinst du das?

**Comment by alexplusde** [comment]
Wenn ich mich im Linkmap-Popup befinde, wäre es komfortabel, über eine Suche direkt den richtigen Artikel oder die richtige Kategorie anzuspringen.

**Comment by skerbis** [comment]
Ich würde hier erstmal abwarten, wie sich der Strukturumbau entwickelt. Es gibt dort auch Bestrebungen eine schnellnavi coreseitig zu realisieren.

**Comment by skerbis** [comment]
Ist in Vorbereitung.

**Comment by skerbis** [comment]
in der aktuellen Github-Version

**Comment by alexplusde** [comment]
Genial.
