### ISSUE TITLE
Bei Eingabe falscher Artikel-ID verschwindet die Strukturverwaltung

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#44]

**Comment by skerbis** [comment]
Hier müsste wie unter REX4 eine Fehlermeldung oder ähnliches kommen. Ich hatte dazu auch mal ein Issue angelegt

**Comment by skerbis** [comment]
https://github.com/redaxo/redaxo/issues/991

**Comment by IngoWinter** [comment]
ich finde, dass wir das durchaus in quick_navigation abfrühstücken können. vom core aus wird da nix kommen, weils mit core-bordmitteln auch nicht wirklich vorkommen dürfte.
mein pr verhindert einfach das abschicken des formulares, wenn keine gültige artikel id im suchfeld hinterlegt ist. ist keine sichere lösung, da ich nicht wirklich prüfe, ob es einen artikel mit der entsprechenden id gibt - dürfte aber zumindest gegen versehentliches id falsch eintippen in den meisten fällen helfen.

**Comment by tbaddade** [comment]
Damit könnte man aber keinen normalen Artikel mehr aufrufen.

**Comment by skerbis** [comment]
@tbaddade @IngoWinter Hier soll die IP eines beliebigen Artikels eingegeben werden. Das Problem ist nicht QuickNavigation. REDAXO selbst liefert keine Regel für Falscheingaben. Ich weiß aktuell nicht, wie ich das in QuickNavigation abfangen kann

**Comment by IngoWinter** [comment]
@tbaddade jau, hab ich nicht auf dem schirm gehabt. dann taugt das natürlich nix  ^^

**Comment by skerbis** [comment]
Dennoch danke für den PR. Den kann ich sicher wo anders gebrauchen 👍

**Comment by tbaddade** [comment]
Betrifft auch das Filtern des Dropdowns. 

Gibt man etwas ins Suchfeld ein und es erscheint nur eine Option, könnte man nach Enter direkt auf diesen Kategorie/Artikel springen. Aktuell verschwindet nach einem "Enter" die Strukturverwaltung.

**Comment by skerbis** [comment]
Ja man muss das Gefundene auch anklicken. Mal schauen ob man das irgendwie lösen kann. @tbaddade da bräuchte ich etwas js Hilfe.

**Comment by tbaddade** [comment]
> da bräuchte ich etwas js Hilfe

vielleicht kannst ja den `selectpicker` mit der `live-search` verwenden. Da kann man mit den Pfeiltasten in der Liste navigieren. Bis jetzt kommt man scheinbar via Tastatur nicht in de Liste.

**Comment by skerbis** [comment]
@tbaddade ja wäre möglich, aber das Menü müsste dann erstmal zu einem Select-Menü umgebaut werden, bzw. wieder zurück gebaut werden.

**Comment by skerbis** [comment]
Die Eingabe der Artikel-ID wird entfernt und steht ja in Watson bereits bereit. In REX5 ist die ID ohnehin nicht mehr so wichtig.

**Comment by tbaddade** [comment]
@skerbis Warum schließt du das Issue? Der Fehler ist damit nicht beseitigt. Die Struktur kann weiterhin ohne Inhalt erscheinen.

**Comment by skerbis** [comment]
@tbaddade ja stimmt,  aber nicht mehr bei Quick Navigation. Das muss im Core gelöst werden.  Die Eingabe einer ID und Bestätigung per Enter wird vorerst entfernt.  
Das eigentliche Issue sollte hier gelöst werden:
https://github.com/redaxo/redaxo/issues/991
