### ISSUE TITLE
cache busting für die assets

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/quick_navigation#46]
die assets bekommen die versionsnummer des addons als buster mit und nicht wie eigentlich von redaxo vorgesehen den timestamp der letzten dateiänderung. das ist zum entwickeln etwas nervig. gibts dafür einen grund oder kann das weg?

**Comment by skerbis** [comment]
Wer hat den Timestamp vorgesehen? … ich weiß von Nichts

**Comment by skerbis** [comment]
Gab's den buster schon in 5.1.0?

**Comment by skerbis** [comment]
Lt. Changelog erst seit 5.4. Damit ist es für mich erledigt, so lange QN nicht mindestens 5.4 benötigt.

**Comment by IngoWinter** [comment]
och komm ey ^^
schlimmstenfalls muss einer mit ner veralteten redaxo version seinen cache leeren. und die leuts, die auf ner 5er version < 5.3 rumeiern und peinlich drauf achten dass alles ausser dem core aktuell ist, kannste wahrscheinlich an einer hand abzählen.

**Comment by skerbis** [comment]
Aber nur weil Düs so lieb bitte bitte gesagt hast https://github.com/FriendsOfREDAXO/quick_navigation/commit/bff944aaabb0402798489d496efd036c8351b6bb

**Comment by IngoWinter** [comment]
@skerbis mille grazie :)

**Comment by tbaddade** [comment]
Mindesrversion von Redaxo würde ich in der Package.yml auf 5.3 anheben.

**Comment by schuer** [comment]
Oh, Cache-Warmup macht das auch so mit der Versionsnummer als Buster. War eine Zeit lang mal sowas wie Best Practice. Ich hatte den Timestamp-Buster seit 5.3 gar nicht mitbekommen, danke euch für die Info! Werde dann beim Warmup auch mal switchen.
