### ISSUE TITLE
YForm Tabellen listen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#47]
### Sprung zur 

- **Datentabelle**
   Url: `/redaxo/index.php?page=yform/manager/data_edit&table_name=rex_news`
- **Tabelle editieren**
    Url: `/redaxo/index.php?page=yform/manager/table_edit&start=0&func=edit&table_id=5`
- **Felder bearbeiten**
    Url: `/redaxo/index.php?page=yform/manager/table_field&table_name=rex_news`

**Comment by skerbis** [comment]
Ja, eine gute Idee, wenn ich nur wüsste wohin und vor allem welche? Es muss ja auch je User geprüft werden auf welche Tabellen er Zugriff hat.

**Comment by tbaddade** [comment]
> Es muss ja auch je User geprüft werden auf welche Tabellen er Zugriff hat.

Alle Tabellen holen
https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Workflows/YForm/YFormSearch.php#L66

Auf Rechte prüfen
https://github.com/tbaddade/redaxo_watson/blob/master/lib/Watson/Workflows/YForm/YFormSearch.php#L72

**Comment by skerbis** [comment]
Die Frage ist, wo stellt man die Auswahl zur Verfügung?

**Comment by skerbis** [comment]
Auch vom User auswählbar?

**Comment by tbaddade** [comment]
> Auch vom User auswählbar?

Ja, sobald er Rechte daran hat.

**Comment by skerbis** [comment]
Ich meine meine eine Auswahl wie bei den Favoriten

**Comment by tbaddade** [comment]
Würde ich am Anfang nicht machen. Erstmal das Dropdown-Menü mit den Tabellen erstellen und dann weiter sehen.

**Comment by skerbis** [comment]
Es wird eine Auflistung der Tabellen werden mit der direkten Möglichkeit neue Datensätze anzulegen. 
Tabelle / Felder editieren sehe ich hier nicht.

**Comment by tbaddade** [comment]
> Tabelle / Felder editieren sehe ich hier nicht.

Grad den Part braucht man als Admin eher.

**Comment by skerbis** [comment]
Für mich ist QuickNavigation eher ein Werkzeug für den Redakteur um sich im System schneller zurecht zu finden. Die Admin-Extras sind doch eher was für Watson oder? Watson hat doch schon so viele nette Admin Goodies.

**Comment by tbaddade** [comment]
Ok dann kommt das in den Watson :)

**Comment by skerbis** [comment]
@tbaddade zack! feddich

**Comment by skerbis** [comment]
Ach ja, Danke @chrison94
