### ISSUE TITLE
Direkt in Artikel springen wie bei be_search in R4

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/quick_navigation#5]
ID in ein Feld eingeben und zack bin ich beim Artikel. Manchmal extrem praktisch. Gerne auch zusätzlich eine Suche nach Namen, wie es das auch bei be_search gab..

**Comment by tbaddade** [comment]
Duplicate #1

**Comment by skerbis** [comment]
Das separate Eingabe-Feld für die ID entfällt in 2.0, ist dann kombiniert mit dem Filter.
