### ISSUE TITLE
Umbruch bei mobiler Darstellung

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/quick_navigation#50]
Wenn man sämtliche Schaltflächen von QuickNavigation nutzt, brechen in der mobilen Darstellung Symbole um. _(Getestet: iPhone SE - 2 Symbole, Galaxy S8 1 Symbol)_
Vllt. wäre es interessant, das anzupassen, zumal die QuickNavi mit der neuen Sked-Terminsfunktion geradezu prädestiniert ist für mobile Nutzung...
<a href="http://abload.de/image.php?img=screenshot4zqfb.png"><img src="https://abload.de/thumb/screenshot4zqfb.png" /></a>

**Comment by skerbis** [comment]
Ist ein allgemeines Problem in REDAXO.  Eine Bedienung auf dem Smartphone ist aktuell nicht sehr komfortabel. Aber wir lassen uns was einfallen.

**Comment by skerbis** [comment]
Wird sich durch das 3.0 Konzept ändern https://github.com/FriendsOfREDAXO/quick_navigation/projects/1?
