### ISSUE TITLE
title auf dem "auge" symbol

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/quick_navigation#51]
ein title tag/mouseover text auf dem auge in der quick nav wäre toll, damit man schon vorm klicken sehen kann was passieren wird wenn man drauf drückt

![image](https://user-images.githubusercontent.com/120441/34456611-288221d0-ed9b-11e7-9d76-e96f6b431f34.png)

**Comment by chrison94** [comment]
habs reingepackt :-)

**Comment by staabm** [comment]
danke
