### ISSUE TITLE
Feature-Wunsch: Artikel schnell finden

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/quick_navigation#52]
Die Quick-Navigation ist superpraktisch! Vielen Dank!
Doch wieso nicht die Artikel-ID eingeben können zum schnellen Finden? Ich verstehe nicht, warum das auf Cat-IDs beschränkt ist.
Wäre mein Wunsch, lieber Thomas.
Viele Grüße Heinz

**Comment by skerbis** [comment]
@erraiva einfach Watson installieren. Darin steht die Funktion zur Verfügung

**Comment by erraiva** [comment]
Ja, vielen Dank, das wusste ich nicht.
LG Heinz
