### ISSUE TITLE
Quicknavigationsmenü erscheint immer

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/quick_navigation#54]
Ich habe z.b. einen REDAXO User mit der Rolle, nur Tabellen zu pflegen, hat also keinen Zugriff auf Kategorien oder COntent, dennoch sieht er die Quicknavi im Menü link. Ich würde davon ausgehen, dass diese dann nicht auftauchen sollte.

quick_navigation | 2.2.6

<img width="558" alt="bildschirmfoto 2018-01-19 um 15 08 12" src="https://user-images.githubusercontent.com/322951/35154462-9ae07288-fd2a-11e7-8854-bbabccd986ed.png">

**Comment by skerbis** [comment]
Wenn du ihm das Recht für die QuickNavi entziehst, ist es nicht weg?

**Comment by skerbis** [comment]
Ich verstehe das Problem. Auch zeigt die Category-Select alle Kategorien. Ich dachte, sie prüft die Rechte automatisch. – Gerne n PR. Komme jetzt auf die Schnelle nicht dazu.

**Comment by skerbis** [comment]
@dergel entferne vorerst erstmal das QuickNavi recht bei dir. Macht ja in Deinem Szenario gerade eh nicht viel Sinn. Problem ist notiert.

**Comment by skerbis** [comment]
@dergel 
https://github.com/FriendsOfREDAXO/quick_navigation/releases/tag/2.3.0
<img width="1166" alt="bildschirmfoto 2018-01-19 um 21 57 40" src="https://user-images.githubusercontent.com/791247/35171927-c30d0b5a-fd65-11e7-9992-20262947d5f4.png">
