### ISSUE TITLE
Buttons zum Sortieren des Medienpools

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#55]
Vorerst: Nach Filname und default nach Datum

**Comment by tbaddade** [comment]
Gehört für mich nicht in dieses Addon.

**Comment by skerbis** [comment]
Es beschleunigt die Navigation. Wo gehört es denn Deiner Meinung hin?  Gegenvorschlag?

**Comment by tbaddade** [comment]
Structure Tweaks (so lang es nicht im MP 3 enthalten ist)
1/ wenn das umbenannt wird
2/ da man sortieren auch gut in der Struktur oder an anderen Stellen gebrauchen kann.

**Comment by skerbis** [comment]
Akzeptiert
