### ISSUE TITLE
Off-Canvas anstelle Drop-Down

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#56]

**Comment by skerbis** [comment]
erstmal nicht

**Comment by staabm** [comment]
was wäre der vorteil von "off-canvas" und was genau ist damit gemeint?

**Comment by skerbis** [comment]
Dachte an eine Off-Canvas-Sidebar / oder overlay, die wie die macOs Nachrichtenzentrale arbeitet. So mehr Platz für die Navigation bietet. Evtl. sogar Tab getrennt um zwischen den Funktionen zu switchen. Auch mobil sind solche Lösungen besser. Aktuell sind es schon einige Buttons in der QN. Ich denke das könnte man reduzieren.
