### ISSUE TITLE
YForm Tabellennamen-Strings mit translate: werden nicht übersetzt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/quick_navigation#58]
Betrifft bspw. die Tabellennamen des Community-Addons

**Comment by skerbis** [comment]
Ist mir auch aufgefallen. Hat wer einen Tipp wie man das lösen kann? @alexplusde  @tbaddade

**Comment by alexplusde** [comment]
Am besten so lösen, wie YForm das löst - bspw. sind auch Tabellen, die nicht im Menü erscheinen sollen, in der Quick Navigation sichtbar.

**Comment by tbaddade** [comment]
> Hat wer einen Tipp wie man das lösen kann?

Ich nutze dafür `$table->getTableName()`.

**Comment by skerbis** [comment]
Benutze ich auch
Bringt nichts, da durch yCom übersetzt? https://github.com/FriendsOfREDAXO/quick_navigation/blob/050bd8d7301b55aaf690562e52bde48e99b42d10/fragments/quick_yform.php#L20

**Comment by tbaddade** [comment]
Hab gard mal nachgesehen. So wäre es wohl korrekt: `rex_i18n::translate($table->getName())`

**Comment by skerbis** [comment]
Danke. Ist in der nächsten Release: https://github.com/FriendsOfREDAXO/quick_navigation/commit/a6ca5bcb8cc15edde53aa4d61550e3f9c45ab870

**Comment by alexplusde** [comment]
Und Tabellen, die in der Navi ausgeblendet werden sollen?

**Comment by alexplusde** [comment]
So macht's YForm: Tabellen abfragen, Status berücksichtigen, Übersetzen:
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/boot.php#L15-L68

**Comment by skerbis** [comment]
@alexplusde ist doch schon im Repo. Wie gesagt, kommt im nächsten Release.
