### ISSUE TITLE
Kompatibilität zu YRewrite-Domains

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/quick_navigation#6]
Mit einer 2. YRewrite-Domain wird die Darstellung der einzelnen Kategorien ziemlich unbrauchbar, weil viel zu umfangreich. Es wäre klasse, wenn die QuickNavigation bei mehr als einer YRewrite-Domain zunächst eine Domainauswahl vorschaltet.

**Comment by skerbis** [comment]
Hast n Tipp oder PR? @alexplusde

**Comment by tbaddade** [comment]
Angedacht war hier mal, dass nur der Baum der aktuellen Domain zu sehen ist. Wird aber schwierig sobald eine Domain in einer anderen gemounted wird und wenn man sich grad außerhalb der Struktur befindet.

**Comment by skerbis** [comment]
Nein, da die Verwendung unterschiedlicher Domains mit  yrewrite sehr unterschiedlich ausfallen kann.

**Comment by skerbis** [comment]
Ok ... wie erhalte ich a) die Liste der Domains? , b) die Startartikel der jeweiligen Domains, c) wie finde ich heraus ob in yrewrite überhaupt Domains hinterlegt sind oder ob nur der Rewriter verwendet wird.

**Comment by alexplusde** [comment]
@dergel kannst du was dazu sagen?

**Comment by IngoWinter** [comment]
Ich habe die Tage wieder eine Multidomainseite, dann könnte ich das einbauen. Ich würde es so machen, dass ich prüfe ob yrewrite aktiv ist und ob mehr als eine domain hinterlegt ist. Wenn ja, hole ich pro domain die letzten 15 Artikel und es gibt oberhalb der Items ein select mit den Domains. Initial steht das select auf "alle Domains" und pro Artikel wird die dazugehörige Domain eingeblendet. Wählt der Nutzer eine Domain aus werden nur noch die zur Domain gehörigen Artikel ausgegeben und die Zusatzinfo Domain bei den Artikeln kann ausgeblendet werden. Die Auswahl des Nutzers wird über localstorage gespeichert.

![quicknavi_multidomain](https://cloud.githubusercontent.com/assets/7223820/22858553/6613c788-f0c1-11e6-841e-b5e880332be7.png)

Wie sieht das mit Nutzerrechten für Artikel aus? Das wird aktuell nicht geprüft, der Nutzer bekommt auch Artikel angezeigt, die er gegebenenfalls gar nicht bearbeiten darf. Ist das Absicht oder soll ich das berücksichtigen?

**Comment by skerbis** [comment]
Der User bekommt je nach Recht alle Artikel oder  die Artikel zu sehen die er bearbeitet hat. 
https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/lib/QuickNavigation.php#L25

**Comment by skerbis** [comment]
Das war einfacher als jedes mal eine Rechteprüfung durchzuführen. 
Ich sehe keinen Grund bei einer Hostory von 15 Artikeln nach Domains zu unterscheiden. Domains sind in yform nur Kategorien. Ein Artikel könnte im ungünstigen Fall sogar zwei oder mehr Domains zugeordnet sein. (Je nach Verschachtelung)

**Comment by alexplusde** [comment]
(Mir ging es ursprünglich um den Kategorie-Baum, nicht um die History.)

**Comment by IngoWinter** [comment]
@skerbis ein Artikel kann immer nur einer Domain zugeordnet sein, auch wenn verschachtelte Mountpoints in yrewrite möglich sind.
@alexplusde wie könnte sowas denn aussehen? soll ja ne Schnellnavigation sein, son Filterdingens wie du da verlinkt hast ist dann ja doch eher suboptimal. Letztendlich fällt mir da nicht viel anderes zu ein als ein Overlay mit Baumansicht...

**Comment by skerbis** [comment]
Ich würde hier auch eher Richtung History tendieren.

**Comment by tbaddade** [comment]
Damit das Backend nicht träge wird, sollte der Baum abhängig zur Domain angezeigt werden. Das war der Killer schlechthin in der 4er Version. Wir mussten dann zumeist die be_search abschalten.

Ich könnte mir das so vor stellen.
Ist man außerhalb der Struktur, werden die Domains mit ihren ersten Rootkategorien angezeigt. Sobald man sich innerhalb einer Domain bewegt, wird der komplette Baum der Domain angezeigt.
Befindet sich ein Mountpoint innerhalb eines anderen, wird nur diese Kategorie ganz oben im baum des anderen Mountpoints angezeigt.

**Comment by skerbis** [comment]
Finde ich etwas verwirrend

**Comment by IngoWinter** [comment]
@tbaddade 
ajax, als json holen und dann in localstorage speichern? relevante änderungen per ep abfangen und die localstorage kopie löschen, dann wieder per ajax holen. sollte doch eigentlich keinen spürbaren einfluss auf die geschwindigkeit des backends haben.

**Comment by tbaddade** [comment]
@IngoWinter Das wäre eine Idee. 

Der Overkill in der 4er Version war, wenn ich das noch richtig in Erinnerung habe, die Rechteabfrage zu jeder einzelnen Kategorie. Das passiert auch bereits in Quicknavigation. Ich wollte nur darauf hinweisen, bevor es hier an das Eingemachte geht.

**Comment by alexplusde** [comment]
Also ich habe gerade gesehen, dass zumindest schon mal ein Kategorien-Filter eingebaut wurde und der Baum nicht mehr voll aufgeklappt ist. 80 Kategorien untereinander hatten das "Quick" nicht verdient @IngoWinter. Das ist schon eine gute Verbesserung!

Aber wenn ich jetzt bspw. Filter, woher weiß ich, in welcher Domain ich mich bewege?
![image](https://cloud.githubusercontent.com/assets/3855487/22877116/2e6d7108-f1d4-11e6-91ee-9560cb9b217b.png)

Bei 3 Websites, die sich die gleichen Menüpunkte-Namen teilen, stünde hier bspw. 3x Vita.

**Comment by IngoWinter** [comment]
@alexplusde also ich hab gar nix gemacht :o)
skerbis und ich haben gestern aber schon mal drüber geschnackt, wie man die kategorien bei mehreren domains darstellen könnte. ich würde eine lösung mit mehreren selects bevorzugen - pro domain eines. gibt es mehr als eine domain, wird nicht mehr direkt das kategorie select ausgegeben, sondern eine schaltfläche "Quicknavi". on click/ hover geht ein dropdown mit mehreren selects auf (eins pro domain). diese verhalten sich dann wie aktuell. 
du bist übrigens herzlich eingeladen, ebenfalls über lösungsansätze zu sinnieren (gerne auch per slack) und diese hier vorzustellen. den status quo mit screenshots dokumentieren brauchste nicht ;)

**Comment by skerbis** [comment]
Der Filter ist doch schon seit 0.1.5 drin ;-) ... man könnte auch einfach dahinter oder darunter die Domain schreiben.  Was hält Ihr davon, wenn einfach neben dem Filter ein Domain-Auswahlfeld gesetzt wird? Per default ist immer die ganze Struktur zu sehen. Man kann aber mit dem Domainfilter dann auswählen welchen Baum man sehen will. So bliebe es immer noch quick.

**Comment by alexplusde** [comment]
@IngoWinter Natürlich dokumentiere ich zur Klärung meines Anliegens das ganze mit Screenshots, schon allein, um Missverständnissen aus dem Weg zu gehen und das Problem zu veranschaulichen. Selbstverständlich bringe ich mich auch mit Lösungsansätzen ein, wenn ich denn hinter einer Idee stehen kann. Bin aber selbst auch noch unschlüssig...

@skerbis die Idee finde ich gut. Vlt. kann der Domainfilter innerhalb der Struktur schon vorausgewählt werden.

**Comment by skerbis** [comment]
Kurz, gibt es eine Funktion die mir die vorhandenen Domains und deren Mountpoints zurückgibt? Dann mache ich das fertig

**Comment by IngoWinter** [comment]
`rex_yrewrite::getDomains()` gibt dir einen array mit domainobjekten zurück

**Comment by skerbis** [comment]
In der aktuellen Github-Version kann man in der Livesuche die Domain eingeben und erhält so schnell den Baum der gewünschten Domain

**Comment by skerbis** [comment]
@alexplusde reicht das?

**Comment by skerbis** [comment]
Ich mache hier erstmal ein Close in 1.2 kommt noch eine Domain-Auswahl dazu (in Arbeit).
