### ISSUE TITLE
Watson reagiert nicht auf Mausklick

### ISSUE THREAD

**Issue by svenkaemper** [FriendsOfREDAXO/quick_navigation#60]
In bestimmten Konstellationen passiert nichts, wenn Watson über das Icon in der QuickNavigation aufgerufen wird. Beispiel:

1. Seite "Module" aufrufen
2. irgendein Modul zum Bearbeiten öffnen
3. dann “Abbrechen” oder "Speichern"
4. Seite "Module" wird erneut angezeigt
5. auf Watson-Icon in Quicknavigation klicken
6. nix passiert

Aufruf über Tastaturkürzel funktioniert jedoch immer; bei abgeschalteter QuickNavi und Aufruf von Watson über das Icon im Header keinerlei Probleme.

(Mac OS 10.13.3, Version Safari 11.0.3)

**Comment by IngoWinter** [comment]
bitte bei watson ein issue aufmachen, liegt nicht an der quicknavi. die watson.js muss angepasst werden https://github.com/tbaddade/redaxo_watson/blob/master/assets/watson.js#L104
