### ISSUE TITLE
Feature-Wunsch: Nur online-Artikel anzeigen

### ISSUE THREAD

**Issue by svenkaemper** [FriendsOfREDAXO/quick_navigation#61]
Wäre schön, wenn man in den Einstellungen festlegen könnte, dass im Menü nur Kategorien und Artikel angezeigt werden, die aktuell "online" sind.

**Comment by skerbis** [comment]
Da es sich hier um eine Backend-Navigation handelt, sehe ich den Sinn nicht.

**Comment by svenkaemper** [comment]
Es macht Sinn, wenn das Backend hauptsächlich von Redakteuren zur Pflege bestehender Seiten genutzt wird. Ich habe aktuell einen Fall, bei dem einige Bereiche (Kategorien inkl. Unterkategorien und Artikel) einer Website temporär „offline“ gesetzt sind, und die Redakteure meckern, weil diese Seiten in der Quicknavi nach wie vor auftauchen und sie so viel scrollen müssen… 

Natürlich könnte man den Zugriff auf die entsprechenden Kategorien über die Rollen-Einstellungen beschränken, aber dann ist wieder ein manueller Eingriff nötig und man muss daran denken, den Zugriff bei Status-Änderungen wieder anzupassen.

Vielleicht gibt's für den beschriebenen Fall aber auch eine andere Lösung, die ich momentan nicht sehe? Mir fiel spontan eben eine Checkbox "Nur Online-Artikel anzeigen" in den Einstellungen der QuickNavi ein.

**Comment by staabm** [comment]
ggf. wäre es sinnvoll dass man als user der quicknavi eine checkbox hat, wo man anlicken kann ob man offline sehen will oder nicht
(den wert der checkbox dann via localstorage/cookie merken und autom. so benutzen)

**Comment by skerbis** [comment]
Na ja, häufig sind Offline-Artikel nur offline, weil sie nicht in der Navi gezeigt werden sollen, aber dennoch zentrale Informationen bereitstellen oder eben Seiten beinhalten die anders aufgerufen werden als über die Navi. Man müsste es dann auch synchron zur Struktur machen. Dann sollte diese Kategorien auch nicht anzeigen. Sehe das eher in der Rolleneinstellung oder im Profil des Users, weniger in der Quicknavi.

**Comment by tbaddade** [comment]
> Na ja, häufig sind Offline-Artikel nur offline, weil sie nicht in der Navi gezeigt werden sollen, aber dennoch zentrale Informationen bereitstellen oder eben Seiten beinhalten die anders aufgerufen werden als über die Navi.

Das ist reine Vermutung, davon würde ich so nicht ausgehen. Und da es ja Bedarf zu geben scheint, warum nicht nach off-/online filtern lassen?

>  Man müsste es dann auch synchron zur Struktur machen.

Müsste man nicht. Über die QN soll man schneller zum Ziel kommen als über die Struktur. Warum müssen beide hier dasselbe Verhalten haben?

**Comment by skerbis** [comment]
Na gut

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/commit/a9f8977d90cb8f4f811e5e900f735c8eda3162bd @svenkaemper  @tbaddade  bitte aktuelle Github-Version testen.
