### ISSUE TITLE
Quick Navigation im Medienpool - Rechte werden nicht berücksichtigt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/quick_navigation#62]
Ich beschränke in einer Rolle den Zugriff auf eine Medienkategorie - im Quicknavigation waren jedoch weiterhin alle sichtbar. R5.3 / QN 2.0.2

**Comment by tbaddade** [comment]
Ist korrektes Verhalten. Siehe auch https://redaxo.org/doku/master/benutzerverwaltung#rollemedienordner

**Comment by alexplusde** [comment]
Danke für die Klarstellung
