### ISSUE TITLE
placeholder text für "normale user" verbessern

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/quick_navigation#64]
Ich denke dieser placeholder text könnte noch verbessert werden, damit ein unbedarfter user besser weiß was er alles eingeben kann.

- `CatId` als begriff ist sonst im backend nicht gebräuchlich
- Was bedeutet `Filter`?

![image](https://user-images.githubusercontent.com/120441/40013474-e623b07e-57ad-11e8-91db-e586bdc44a25.png)

**Comment by staabm** [comment]
vom text her finde ich das gut. rein aus neugier: mit welchem suchbegriff suche ich nach "Domain"?

**Comment by skerbis** [comment]
Evtl. sollte ich Domain weglassen und erst anzeigen, wenn yrewrite installiert ist

**Comment by skerbis** [comment]
<img width="496" alt="bildschirmfoto 2018-05-14 um 21 08 12" src="https://user-images.githubusercontent.com/791247/40017883-fc270698-57ba-11e8-8cfd-252649bbbc37.png">
sieht jetzt erstmal so aus

**Comment by staabm** [comment]
passt für mich, ist auf jeden fall besser als der status quo.
