### ISSUE TITLE
Update auf PHP 7.2 - Favoriten für zu count()-Warnung

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/quick_navigation#75]
Reproduzieren: 
- Quick Navigation installieren
- PHP auf 7.2 updaten
- Backend-Warnung 

Workaround:
- Einstellungsseite der Quick Navigation aufrufen und 1x speichern

**Comment by skerbis** [comment]
Bitte mit aktueller GitHub-Version noch mal testen. @alexplusde  Danke für den Hinweis

**Comment by skerbis** [comment]
sollte behoben sein https://github.com/FriendsOfREDAXO/quick_navigation/blob/7d95f015b176a2e865e0c6a47ea6935cc0ac32c6/fragments/quick_favs.php#L15
