### ISSUE TITLE
Noch ne notice im medienpool

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/quick_navigation#79]
`Notice: Undefined variable: custom_media in /Users/aaa/Sites/bbb/redaxo/src/addons/quick_navigation/lib/QuickNavigation.php on line 24`

**Comment by skerbis** [comment]
grr warum kommen die bei mir nicht?

**Comment by staabm** [comment]
seit redaxo 5.6 kannst du auch in der config.yml das error reporting so einstellen dass du auch für notices/warnings eine whoops-fehlerseite bekommst

https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/default.config.yml#L4

**Comment by skerbis** [comment]
Jo das ist klar, dennoch bekam  ich die nicht. @staabm - irgendein anderes AddOn hat die unterdrückt, denke ich. Hab meine Demo mal zurückgesetzt - alles wieder ok
