### ISSUE TITLE
Buttonstyle fehlt in der aktuellen Version

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#81]

**Comment by skerbis** [comment]
Ja das ist Absicht und wurde der Community auch vorher vorgestellt. Gründe: b) mobil wird man nicht gleich von den Buttons erschlagen, b) die Darstellung ist etwas zurückhaltender. Da wo es jedoch Sinn macht (Medienpool und Linkmap) sind es weiter Buttons, da sie sich den vorhandenen Balken/Buttons eingliedern.

**Comment by tbaddade** [comment]
Wenn das Absicht ist kannst ja das Issue schließen, solltest nur nochmal drübergehen.  Man sieht bei active den Hintergrund aber nicht die Schrift. Auch sollte das Dropdown m.E. überarbeitet werden, so dass es mit den "Buttons" wieder besser harmoniert.

Insgesamt fand ich die vorherige Version aber angenehmer.

**Comment by skerbis** [comment]
...active den Hintergrund aber nicht die Schrift? Screenshot? Browser?

**Comment by tbaddade** [comment]
> ist mir nicht ganz klar

Click mal auf den Watson :)

**Comment by skerbis** [comment]
![bildschirmfoto 2018-07-06 um 11 08 46](https://user-images.githubusercontent.com/791247/42370413-f97f2062-810c-11e8-9cd5-7d37b5486c64.png)
Weiß nicht was du meinst

**Comment by skerbis** [comment]
Du meinst, beim Klick? Korrekt? Ok .. das ist aber eher ein Problem der Watson Stile selbst. Bitte mal ohne Quick Navi schauen. Da ist das Watson-Symbol auch beim Klick weg.

**Comment by tbaddade** [comment]
Ich kann davon keinen Screen machen. Klick und halte den Watson Button. Das Icon "verschwindet" derzeit. Es kommt nur noch der Hintergrund angezeigt.

**Comment by tbaddade** [comment]
> Bitte mal ohne Quick Navi schauen. Da ist das Watson-Symbol auch beim Klick weg.

Recht haste. Kommt direkt von BS3.

**Comment by skerbis** [comment]
Kannst du das Watson symbol nicht etwas dunkler machen?

**Comment by tbaddade** [comment]
D.h. du bleibst jetzt bei diesem Style für die Struktur?

**Comment by skerbis** [comment]
Habe einige Rückmeldungen bekommen und die waren durchweg positiv mit einer Ausnahme. Ich kann es auch per Setting für die User anbieten, wenn du möchtest.

**Comment by skerbis** [comment]
Bis auf die Linien nice

**Comment by skerbis** [comment]
![bildschirmfoto 2018-07-06 um 16 15 47](https://user-images.githubusercontent.com/791247/42384304-ea6e7faa-8139-11e8-8127-261106148f14.png)

aktueller Stand mit alternativer Leiste

**Comment by tbaddade** [comment]
Was ist die "alternative Leiste" ?

**Comment by skerbis** [comment]
Buttons ohne Rahmen ... 
Wie gesagt. Wenn ich dafür ein Setting anlegen würde, oder du die Settings erweiterst, könnte man Deine Darstellung als skin anbieten

**Comment by skerbis** [comment]
Jeder User kann sich dann auswählen was ihm lieber ist

**Comment by tbaddade** [comment]
> Wenn ich dafür ein Setting anlegen würde, oder du die Settings erweiterst, könnte man Deine Darstellung als skin anbieten

Dann sollte man zuvor über das Markup/Klassen und das CSS noch mal gehen. Damit es einfacher ist ein Skin anzubieten. Meine Korrekturen kann man so nicht wirklich ausliefern ;)

**Comment by skerbis** [comment]
Ist bei mir doch auch nur "Gefummel" wie man so schön sagt. Ich überschreibe ja die REDAXO eigenen Stile.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/issues/82
