### ISSUE TITLE
Wishlist: / Eure Ideen hier

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#82]
Skin/Theme Support

**Comment by alexplusde** [comment]
Würde vorschlagen, durch die Auslagerung in Fragmente sich hier an den Values von YForm zu orientieren und die Fragmente in `fragments/bootstrap3/fragment.php` zu organisieren. So wäre man offen. 

Wie macht @joachimdoerr das denn für mform? 

Stelle allerdings die Notwendigkeit grundsätzlich infrage, da mehr zu machen: Es muss erstmal ein Szenario geben, in dem großflächig auf ein anderes Theme/Framework umgestellt wird.

**Comment by skerbis** [comment]
bleibt erstmal so wie es ist
