### ISSUE TITLE
Notice: Undefined variable: domaintitle

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#83]

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/blob/40bd16f08a42cc4c26a72c6c1025878f2963e076/fragments/quick_articles.php#L12 

?

**Comment by tbaddade** [comment]
> ? 

Da fehlt ein ` = ''`.

Mach mal das, damit du die Notices zu sehen bekommst
https://github.com/FriendsOfREDAXO/quick_navigation/issues/79#issuecomment-401804089

**Comment by skerbis** [comment]
habe den Fehler entdeckt und gefixt. Ich weiß jetzt auch welche bekloppte AddOn schuld ist, dass die Notices nicht angezeigt werden.

**Comment by staabm** [comment]
Welches? :-)

**Comment by skerbis** [comment]
Kein Community AddOn, extern programmiert, nicht im Installer.
