### ISSUE TITLE
Warning: Undefined variable "mode" nach update

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/quick_navigation#84]
`Warning: Undefined variable "mode" in rex_fragment "quick_favs.php" in /homepages/.../htdocs/beta/redaxo/src/core/lib/fragment.php on line 213`

**Comment by skerbis** [comment]
Nach dem Reload sollte es weg sein - oder?
@alexplusde -- Ich weiß nicht wie ich dieses Notice vermeiden kann

**Comment by alexplusde** [comment]
das stimmt.

**Comment by skerbis** [comment]
Anscheinend wird das Fragment bereits aufgerufen obwohl die neue Class noch nicht geladen ist. (Ist meine Vermutung) @gharlan ?

**Comment by skerbis** [comment]
Ich kann den Fehler mit der aktuellen 3.3.0 nicht reproduzieren. @alexplusde Wie sieht's bei Dir aus?

**Comment by alexplusde** [comment]
3.3 ist noch nicht im Installer, oder? Es geht sicherlich darum, wenn man aus einer Version updatet, die `mode` noch nicht im Fragment hatte, hin zur Version, die sie einsetzt.

Ich denke mal, das hat hiermit zu tun: https://github.com/redaxo/redaxo/issues/702#issuecomment-359547286

**Comment by skerbis** [comment]
3.3 ist im Installer - ok, dann liegt das Problem mit der notice wohl nicht bei mir. Danke

**Comment by alexplusde** [comment]
Habe mir nochmal darüber Gedanken gemacht.

Das Fragment sollte vorab prüfen, ob `$this->mode` (und andere) existiert. Das Problem hatte ich in meinem DSGVO-Addon auch, wenn ich nachträglich Parameter in das Fragment hinzufüge. Hier ist es überschaubar, weil ja nach dem Reload die Variable zur Verfügung steht.

**Comment by skerbis** [comment]
erledigt... kommt mit dem Service-Release 3.3.1

**Comment by skerbis** [comment]
ne doch nicht
