### ISSUE TITLE
direkte Artikel-ID Eingabe

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/quick_navigation#86]
Früher ging as doch, dass ich auch Artikel, die kein Startartikel waren, aufgelistet bekam. Oder zumindest per ID direkt aufrufen kann. 
Das feature finde ich total nützlich und ich bedaure, dass es (meiner Erinnerung nach) erst kürzlich ausgebaut wurde. Lässt sich das wieder reaktivieren, zur Not per Einstellung?

**Comment by cukabeka** [comment]
Hm, ging aber in R4 doch, oder? Und am Anfang in R5 auch, glaube ich… Warum ist das denn ein "wontfix"? Hat sich die Architektur grundlegend geändert? Hatte mit @thielpeter kürzlich gesprochen, er hat das auch so in Erinnerung. 
An sich wäre das UI-mäßig kein Thema, auf der Settings-Page auch noch diese Option anzubieten.

**Comment by skerbis** [comment]
@cukabeka es war anfangs drin - ja. Dies führte jedoch zu Problemen, da hier auch eine Suche hätte geschaltet werden müssen oder REDAXO eine Fehlerseite darstellen müsste wenn die ID-Eingabe falsch ist. Mit den zur Verfügung stehenden EPs kannst du das jedoch leicht nachrüsten.

**Comment by skerbis** [comment]
Ich mach das wieder auf … mal schauen

**Comment by tbaddade** [comment]
Bin da bei @skerbis und gehört für mich nicht in dieses AddOn.

**Comment by thielpeter** [comment]
Aber gerade die Navigation zu Artikeln ist doch ein zentrales Feature einer solchen Quicknavigation. Wieso sollte man denn Artikel anders als Kategorien behandeln? Und ein Fehlerhinweis bei nichtsbestehen eines Artikels ist doch kein Problem oder schätze ich das falsch ein?

**Comment by skerbis** [comment]
Das Vorhalten von Artikeln in Quick Navigation würde zu lange Ladezeiten verursachen, wenn der Baum komplett geladen wird.

**Comment by thielpeter** [comment]
Es muss ja nicht der gesamte Baum geladen werden. Es geht ja nur darum das ich in der Suche eine ID eingebe und dann per Ajax geprüft wird ob es den Artikel gibt, dann Ausgabe und wenn nicht Fehlermeldung.

**Comment by skerbis** [comment]
Dazu ist Watson da

**Comment by thielpeter** [comment]
Aber warum sollte ich denn für dieses kleine Feature ein ganzes Addon installieren müssen, und wieso soll der Kunde an zwei unterschiedlichen Stellen arbeiten?

**Comment by skerbis** [comment]
Es ist kein "triviales" Feature. Auch hier wirst du eine Suche benötigen. Diese Aufgabe erfüllt Watson aber perfekt. Es macht keinen Sinn Features zu doppeln.

**Comment by thielpeter** [comment]
Ich benötige ja prinzipiell nur die Navigation per Artikel-ID, nicht die Suche nach einem Artikelnamen :/

**Comment by skerbis** [comment]
Wenn du nur die ID als eingeben möchtest um zu "springen" 
schleuse folgenden Code über einen der EPs ein: 

```php	$formurl = rex_url::backendPage('content/edit',
               ['mode' => 'edit',
               'clang' => rex_clang::getCurrentId(),
               'article_id' => '']);
		
		$quickout = '  <div class="col-sm-1 pull-right">
		<form action="'.$formurl.'" method="post">
            <input class="form-control" type="text" name="article_id" placeholder="ID" value="" />
            </form>
        </div>';```

**Comment by cukabeka** [comment]
Hey @skerbis , Danke für die Idee mit dem EP! Was spricht denn dagegen, dass in den Settings eine Option eingerichtet wird, mit der exakt dieser EP-Code eingeschleust wird? Dann wäre das im Addon und alle wären glücklich

**Comment by skerbis** [comment]
@cukabeka weil Quick Navigation sich anders positioniert und nicht die be_navigation aus 3er und 4er Zeiten fortführt. Die EPs sind genau für diesen Zweck da. Es steht Dir frei ein AddOn be_quickid oder so zu schreiben ;-)
