### ISSUE TITLE
Wie kann ich die Quick Navigation erweitern

### ISSUE THREAD

**Issue by mhut47** [FriendsOfREDAXO/quick_navigation#89]
Hallo, 
gibt es eine Möglichkeit die Quick Navigation zu erweitern?
Ich würde gerne ein paar zusätzliche Buttons unterbringen.

**Comment by skerbis** [comment]
Moin,  es gibt ein paar EPs, die Dir sicher helfen dabei: https://github.com/FriendsOfREDAXO/quick_navigation#für-developer 
Hier kannst du einfach beliebigen Content hinzufügen.

**Comment by mhut47** [comment]
Danke
