### ISSUE TITLE
rex_category_select :: Kategorie-Liste nimmt viel Zeit in Anspruch

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#90]
Evtl. per Ajax laden um Verzögerungen zu vermeiden

![bildschirmfoto 2018-10-25 um 15 46 59](https://user-images.githubusercontent.com/791247/47504810-3fe7f080-d86d-11e8-9ff7-892a4275e536.png)

**Comment by staabm** [comment]
Ich glaube es wäre am sinnvollsten die vollständige quick nav erst via ajax nachzuladen

**Comment by tbaddade** [comment]
Die Quicknavi wird immer langsam bleiben, so lange diese `rex_category_select` nutzt. Eventuell könnte es helfen, die aufgebaute Navi zu cachen. 

###### _In Rex4 war es, so dass man `be_search` abschalten musste um flüssig weiter arbeiten zu können._

**Comment by staabm** [comment]
sobald man die quick nav via ajax nachlädt hätte eine langsame quicknavi keinen impact auf das hauptrequest und somit hätten wir eine viel bessere situation wie heute.

im gezeigten profile braucht `rex_category_select` sind es 100ms - was nicht super schnell ist aber auch nicht mega langsam.

**Comment by skerbis** [comment]
Hier zu sei bemerkt, dass die Seite noch nicht live ist und es sind ca. 200 Kategorien
