### ISSUE TITLE
Warning - erscheint nach dem aktualisieren via Installer auf Version 3.5.0

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/quick_navigation#92]
> Warning: Undefined variable "mode" in rex_fragment "quick_articles.php" in /src/core/lib/fragment.php on line 207

**Comment by skerbis** [comment]
Upgrade von welcher Version aus?

**Comment by tbaddade** [comment]
Das hat mit der Vorgängerversion wenig zu tun.
Ich vermute, dass es diese Zeile ist.
https://github.com/FriendsOfREDAXO/quick_navigation/blob/adaa566180fe0e69132a4776429bd21ac1bdcfe2/fragments/quick_articles.php#L14

**Comment by skerbis** [comment]
Danke stimmt, die Zeile kann ist raus. War unnötig.
