### ISSUE TITLE
Button Text ist leer

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/quick_navigation#93]
Aktuelle Version 3.5.0:
Der Text des Buttons fehlt (es steht nichts im Markup) in dem Bereich "Funktionen" eines Artikels UND nach dem Speichern der Metadaten. Kann das jemand nachvollziehen oder ist das nur bei mir so?
Thx.

![quick](https://user-images.githubusercontent.com/1846849/48616464-fd10c880-e993-11e8-94a2-a5f336cec791.png)

**Comment by skerbis** [comment]
Ja, das ist leider so, weil bei diesen Links die Kategorie nicht mitgegeben wird.

**Comment by staabm** [comment]
ist das ein seiteneffekt vom ajax loading oder war das vorher schon so?

**Comment by skerbis** [comment]
Das war bereits vorher so. Die Frage ist, soll ich's hier fixen oder ist es ein core-Thema, siehe Issue bei redaxo dazu

**Comment by skerbis** [comment]
https://github.com/redaxo/redaxo/pull/2249
