### ISSUE TITLE
Minibar-Button Frontend: YForm

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#94]

**Comment by tbaddade** [comment]
Sollte das nicht YForm selber mitbringen?

**Comment by skerbis** [comment]
Das wäre toll, ist aber aktuell in der QuickNavi. Man könnte darüber nachdenken die Quicknavi ähnlich Modular wie die Minibar zu bauen.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/quick_navigation/issues/97

**Comment by staabm** [comment]
Bevor sich yform an der quicknav andocked, sollte es sich in der minibar andocken, oder?

**Comment by tbaddade** [comment]
> Bevor sich yform an der quicknav andocked, sollte es sich in der minibar andocken, oder?

genau das meinte ich. YForm erscheint bereits in der QuickNavi, wird aber von der QuickNavi mitgeliefert. Alles was in der Minibar auftaucht, sollte m.E. jedes AddOn von sich aus mitbringen.

**Comment by staabm** [comment]
> Alles was in der Minibar auftaucht, sollte m.E. jedes AddOn von sich aus mitbringen.

So strikt sehe ich es nicht, aber für manche der punkte stimme ich zu.

**Comment by skerbis** [comment]
#97 Deshalb, alles was AddOn spezifisch ist in QuickNavi auslagern und es den AddOn-Entwicklern überlassen ob sie in der Minibar oder QuickNavi rein wollen oder gar beides.
