### ISSUE TITLE
Minibar-Button Frontend: Article History

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#96]

**Comment by tbaddade** [comment]
Wäre das nicht besser im History PlugIn aufgehoben?

**Comment by skerbis** [comment]
Die Article History … von QuickNavigation ist ja nur eine Liste der zuletzt bearbeiten Artikel. Die möchte ich halt auch ins Frontend bringen. Hat nichts mit dem History Plugin zu tun.

**Comment by skerbis** [comment]
@tbaddade @staabm @schuer Ich möchte die Artikel-History aus QuickNavi ins Frontend bringen. Jetzt stellt sich für mich die Frage, ist es nicht verwirrend für den User wenn die History mal in der Quicknavi (backend) und im Fronten in der minibar ist. 

Wie denkt ihr?

![Bildschirmfoto 2019-03-22 um 17 22 19](https://user-images.githubusercontent.com/791247/54837669-47e67800-4cc7-11e9-9aca-794bb7d74522.png)

**Comment by schuer** [comment]
> Wäre sie dann nicht besser in der Minibar aufgehoben?

Ja, Minibar. Die bezieht sich eindeutig auf den aktuellen Artikel, während die Quicknavi eher ein Verteiler ist, vom aktuellen Artikel weg, oder? Und es wäre einheitlicher in die Minibar, wie du schon sagtest.

**Comment by skerbis** [comment]
diese history zeigt ja unterschiedliche Artikel. Einfach welche Artikel zuletzt geändert wurden.

**Comment by schuer** [comment]
Achso. Na dann spielt das keine Rolle, was ich gesagt habe. Aber deins gilt: Innerhalb der Minibar wäre es im FE und BE einheitlich.

**Comment by skerbis** [comment]
Danke

**Comment by skerbis** [comment]
Ist als Button in der Minibar im Frontend drin
