### ISSUE TITLE
QuickNavi nach Minibar-Vorbild neu entwickeln?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/quick_navigation#97]

**Comment by tbaddade** [comment]
Dann ist die QuickNavi de facto erst einmal ein leerer Container?

**Comment by skerbis** [comment]
Alles was AddOn spezifisch ist ab QuickNavi 4.0 entfernen und es den AddOn-Entwicklern überlassen ob sie in der Minibar oder QuickNavi rein wollen oder gar beides. Sked-Einbindung werde ich übernehmen.

**Comment by staabm** [comment]
Würde ich nicht machen

**Comment by skerbis** [comment]
Nein, kein leerer Container @tbaddade @staabm die Struktur, History, Medienpool also alle Core Sachen wären ja da. Sked-Button würde ich in das Sked AddOn verlagern und YForm nach YForm zudem anderen AddOns ermöglichen sich wie bei der Minibar zu registrieren.

**Comment by skerbis** [comment]
Alternativ kann man es auch lassen und den Stab auch an die minibar übergeben. Ich sehe die Aufgaben der beiden AddOns jedoch unterschiedlich und würde die Minibar ungerne damit "belasten"

**Comment by skerbis** [comment]
Es bleibt erstmal so wie es ist. Ich werde erstmal abwarten wie die Minibar sich entwickelt.
